import test from 'node:test';
import assert from 'node:assert/strict';
import {parse} from '../src/parser.ts';
import * as formatter from '../src/formatter.ts';
const source='// Read the neighboring spec.\nhello(string name) { print(value=$"Hello, {name}!"); print(value="done") }\n';

test('formatter maps individual statements after changing block style and preserves original source ranges',()=>{
 assert.equal(typeof formatter.formatFileWithSourceMap,'function');
 for(const style of ['indent','braces']){
  const result=formatter.formatFileWithSourceMap({config:{block_style:style,indentation:'spaces',assignment:'equals'}},parse('hello.aug',source).file);
  assert.equal(result.text,formatter.formatFile({config:{block_style:style,indentation:'spaces',assignment:'equals'}},parse('hello.aug',source).file));
  const calls=result.mappings.filter(mapping=>mapping.role==='expr');assert.equal(calls.length,2);assert.equal(calls[0].source.line,2);assert.equal(calls[1].source.line,2);assert.notEqual(calls[0].formatted.line,calls[1].formatted.line);
  assert.match(result.text.split('\n')[calls[0].formatted.line-1],/Hello/);assert.match(result.text.split('\n')[calls[1].formatted.line-1],/done/);assert.match(source.slice(calls[0].source.start,calls[0].source.end),/Hello/);
 }
});

test('source ranges exclude trailing comments after indentation blocks',()=>{
 const text='f():\n    if true:\n        print(value=1)\n        // Comment after the call.\n    print(value=2)\n';
 const file=parse('f.aug',text).file;
 for(const style of ['indent','braces']){
  const view=formatter.formatFileWithSourceMap({config:{block_style:style,indentation:'spaces',assignment:'equals'}},file);
  const branch=view.mappings.find(mapping=>mapping.role==='if');assert.equal(branch.source.endLine,3);
  const excerpt=view.text.split('\n').slice(branch.formatted.line-1,branch.formatted.endLine).join('\n');assert.match(excerpt,/if true/);assert.match(excerpt,/value=1/);assert.doesNotMatch(excerpt,/value=2/);
 }
});

test('wiki source navigation preserves statement ranges in both styles and supplies local explanation backlinks',async()=>{
 const {planExampleNavigation,exampleSourceViews}=await import('../scripts/example-source-links.mjs');
 const sourcePath='/project/hello.aug',specPath=sourcePath+'.md',page='docs/examples/hello/hello.md',docs=new Map([[specPath,page]]),sources=new Map([[sourcePath,page]]);
 const artifacts=[{path:specPath,text:'<!-- Generated by aug spec. -->\n\n# `hello.aug`\n\n<a id="symbol-hello"></a>\n\n## `hello` · [source](hello.aug#L2)\n\nIt prints a greeting and then prints done. [source](hello.aug#L2-L2)\n'}];
 const plan=planExampleNavigation(artifacts,docs,sources);assert.match(plan.texts.get(specPath),/hello.md#source-L2-L2/);assert.match(plan.texts.get(specPath),/::: spec-paragraph specification-paragraph-1/);
 for(const view of exampleSourceViews({config:{block_style:'indent',indentation:'spaces',assignment:'equals'}},parse(sourcePath,source).file,source,plan.references.get(sourcePath),page)){
  const reference=view.metadata.links.find(ref=>ref.id==='source-L2-L2');const excerpt=view.text.split('\n').slice(reference.first-1,reference.last).join('\n');assert.match(excerpt,/Hello/);assert.match(excerpt,/done/);assert.deepEqual(reference.backlinks,['#specification-paragraph-1']);assert.equal(view.metadata.sourceSha256.length,64);
 }
});

test('source navigation rendering rejects stale code, invalid ranges and executable backlinks',async()=>{
 const {exampleSourceViews}=await import('../scripts/example-source-links.mjs'),{readSourceNavigation}=await import('../docs/.vitepress/source-navigation.mjs');
 const file=parse('hello.aug',source).file,view=exampleSourceViews({config:{block_style:'indent',indentation:'spaces',assignment:'equals'}},file,source,[{id:'source-L2',sourceFirst:2,sourceLast:2,page:'hello.md',paragraph:'specification-paragraph-1'}],'hello.md')[0];
 assert.equal(readSourceNavigation('aug-source='+view.encoded,view.text).links[0].id,'source-L2');assert.throws(()=>readSourceNavigation('aug-source='+view.encoded,view.text.replace('done','changed')),/differs/);
 for(const change of [value=>{value.links[0].last=999},value=>{value.links[0].backlinks=['javascript:alert(1)']},value=>{value.links.push({...value.links[0]})},value=>{value.extra=true},value=>{value.links[0].id='source-L4-L2'},value=>{value.links[0].id='source-L9007199254740992'},value=>{value.links[0].backlinks=['//outside.example/x.md#section']},value=>{value.links[0].backlinks=['/x.md#section']},value=>{value.sourceSha256=[value.sourceSha256]},value=>{value.links[0].id=[value.links[0].id]},value=>{value.links[0].id=[value.links[0].id];value.links.push({...value.links[0],id:[...value.links[0].id]})}]){const altered=structuredClone(view.metadata);change(altered);assert.throws(()=>readSourceNavigation('aug-source='+Buffer.from(JSON.stringify(altered)).toString('base64url'),view.text),/Invalid|differs/);}
});

test('highlighted HTML gives both styles unique native source anchors and empty accessible prose links',async()=>{
 const {exampleSourceViews}=await import('../scripts/example-source-links.mjs'),{sourceNavigationTransformer}=await import('../docs/.vitepress/source-navigation.mjs'),{createHighlighter}=await import('shiki');
 const {transformerNotationDiff,transformerNotationFocus,transformerNotationHighlight,transformerNotationErrorLevel}=await import('@shikijs/transformers');
 const annotations=[transformerNotationDiff({matchAlgorithm:'v3'}),transformerNotationFocus({matchAlgorithm:'v3'}),transformerNotationHighlight({matchAlgorithm:'v3'}),transformerNotationErrorLevel({matchAlgorithm:'v3'})];
 const highlighter=await createHighlighter({themes:['github-light'],langs:[]});
 try{
  const views=exampleSourceViews({config:{block_style:'indent',indentation:'spaces',assignment:'equals'}},parse('hello.aug',source).file,source,[{id:'source-L2',sourceFirst:2,sourceLast:2,page:'hello.md',paragraph:'specification-paragraph-1'}],'hello.md');
  for(const view of views){const html=highlighter.codeToHtml(view.text,{lang:'text',theme:'github-light',transformers:[...annotations,sourceNavigationTransformer],meta:{__raw:'aug-source='+view.encoded}});assert.match(html,new RegExp('id="source-L2'+(view.metadata.style==='braces'?'-braces':'')+'"'));assert.match(html,/href="#specification-paragraph-1"/);assert.match(html,/aria-label="Read the explanation for this code"/);assert.match(html,/data-aug-source-revision="[a-f0-9]{64}"/);assert.doesNotMatch(html,/>↗</);const copied=html.match(/<code[^>]*>([\s\S]*?)<\/code>/)[1].replace(/<[^>]*>/g,'').replace(/&(?:amp|lt|gt|quot|#39);/g,entity=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'\"','&#39;':"'"})[entity]);assert.equal(copied,view.text);}
 }finally{highlighter.dispose();}
});


test('individual test-case headers map to their own case rather than the enclosing suite',async()=>{
 const {exampleSourceViews}=await import('../scripts/example-source-links.mjs');
 const source='f():\n    pass\n\ntest f:\n    when numbers:\n        it first:\n            assert(true)\n        it second:\n            assert(false)\n';
 const file=parse('tests.aug',source).file;
 for(const view of exampleSourceViews({config:{block_style:'indent',indentation:'spaces',assignment:'equals'}},file,source,[{id:'source-L6',sourceFirst:6,sourceLast:6,page:'tests.md',paragraph:'case-first'}],'tests.md')){
  const link=view.metadata.links[0],excerpt=view.text.split('\n').slice(link.first-1,link.last).join('\n');assert.match(excerpt,/it "first"/);assert.match(excerpt,/assert\(true\)/);assert.doesNotMatch(excerpt,/second|false/);
 }
});

test('shared ranges retain every paragraph and highlighted multi-link menus leave copied source unchanged',async()=>{
 const {planExampleNavigation,exampleSourceViews}=await import('../scripts/example-source-links.mjs'),{sourceNavigationTransformer}=await import('../docs/.vitepress/source-navigation.mjs'),{createHighlighter}=await import('shiki');
 const sourcePath='/project/hello.aug',specPath=sourcePath+'.md',page='docs/examples/hello/hello.md';
 const plan=planExampleNavigation([{path:specPath,text:'First paragraph. [source](hello.aug#L2)\n\nSecond paragraph. [source](hello.aug#L2)\n'}],new Map([[specPath,page]]),new Map([[sourcePath,page]]));
 const views=exampleSourceViews({config:{block_style:'indent',indentation:'spaces',assignment:'equals'}},parse(sourcePath,source).file,source,plan.references.get(sourcePath),page);
 const highlighter=await createHighlighter({themes:['github-light'],langs:[]});
 try{for(const view of views){assert.deepEqual(view.metadata.links[0].backlinks,['#specification-paragraph-1','#specification-paragraph-2']);
  let copied;const text=node=>node.type==='text'?node.value:typeof node.properties?.class==='string'&&node.properties.class.split(' ').includes('vp-copy-ignore')?'':(node.children??[]).map(text).join('');
  const html=highlighter.codeToHtml(view.text,{lang:'text',theme:'github-light',transformers:[sourceNavigationTransformer,{code(node){copied=text(node)}}],meta:{__raw:'aug-source='+view.encoded}});
  assert.match(html,/href="#specification-paragraph-1"/);assert.match(html,/href="#specification-paragraph-2"/);assert.match(html,/aria-label="Read the 2 explanations for this code"/);assert.equal(copied,view.text);
 }}finally{highlighter.dispose();}
});

test('source-linked evidence tables retain table structure and backlink to their named boundary',async()=>{
 const {planExampleNavigation}=await import('../scripts/example-source-links.mjs');
 const sourcePath='/project/hello.aug',artifactPath='/project/hello.aug.diagrams.md',page='docs/examples/hello/hello-diagrams.md';
 const artifact={kind:'diagram',path:artifactPath,text:'<a id="boundary-one"></a>\n\n#### Caller to service\n\n<details>\n<summary>Evidence</summary>\n\n| Caller | Evidence |\n| --- | --- |\n| hello | [source](hello.aug#L2) |\n\n</details>\n'};
 const plan=planExampleNavigation([artifact],new Map([[artifactPath,page]]),new Map([[sourcePath,'docs/examples/hello/hello.md']]));
 const rendered=plan.texts.get(artifactPath);
 assert.match(rendered,/#### Caller to service \{#boundary-one\}/);
 assert.match(rendered,/\| --- \| --- \|\n\| hello \|/);
 assert.doesNotMatch(rendered,/spec-paragraph|<a id=/);
 assert.equal(plan.references.get(sourcePath)[0].paragraph,'boundary-one');
});


test('cross-page code backlinks use real HTML routes and preserve paragraph fragments in both styles',async()=>{
 const {exampleSourceViews}=await import('../scripts/example-source-links.mjs'),{sourceNavigationTransformer}=await import('../docs/.vitepress/source-navigation.mjs'),{createHighlighter}=await import('shiki');
 const references=[{id:'source-L2',sourceFirst:2,sourceLast:2,page:'docs/examples/demo/hello-diagrams.md',paragraph:'specification-paragraph-1'},{id:'source-L2',sourceFirst:2,sourceLast:2,page:'docs/examples/demo/diagrams/index.md',paragraph:'boundary-one'}];
 const highlighter=await createHighlighter({themes:['github-light'],langs:[]});
 try{for(const refs of [references.slice(0,1),references])for(const view of exampleSourceViews({config:{block_style:'indent',indentation:'spaces',assignment:'equals'}},parse('hello.aug',source).file,source,refs,'docs/examples/demo/hello.md')){
  const html=highlighter.codeToHtml(view.text,{lang:'text',theme:'github-light',transformers:[sourceNavigationTransformer],meta:{__raw:'aug-source='+view.encoded}});
  assert.match(html,/href="hello-diagrams\.html#specification-paragraph-1"/);
  if(refs.length===2)assert.match(html,/href="diagrams\/index\.html#boundary-one"/);
  assert.doesNotMatch(html,/href="[^"]*\.md#/);
  assert.ok(view.metadata.links.every(link=>link.backlinks.every(target=>target.includes('.md#'))),'Compiler Markdown metadata remains usable outside the wiki');
 }}finally{highlighter.dispose();}
});
