import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,existsSync,rmSync,mkdirSync,symlinkSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync,spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {realpathSync} from 'node:fs';
import {nativeHostTarget} from '../src/native-contracts.ts';
const cli=resolve('bin/aug.mjs');
const good='double(int value) returns int { return value * 2 }\ntest double { when acceptance { it examples for (value, expected) in [(-3, -6), (0, 0), (7, 14)] { assertEqual(actual=double(value), expected) } } }\n';
const ids=[1,2,3].map(index=>'math.aug:double:acceptance:examples:'+index);
function fixture(run){const root=mkdtempSync(join(tmpdir(),'aug-verification-evidence-'));try{writeFileSync(join(root,'main.aug'),'import double from math\nprint(value=double(value=4))\n');writeFileSync(join(root,'math.aug'),good);writeFileSync(join(root,'requirements.json'),JSON.stringify({format:1,requirements:[{id:'twice',description:'Return twice the input, including negative and zero values.',tests:ids}]}));return run(root);}finally{rmSync(root,{recursive:true,force:true});}}
const invoke=(root,...options)=>spawnSync(process.execPath,[cli,'verify',root,'--requirements','requirements.json','--json',...options],{encoding:'utf8',timeout:90000});

for(const backend of ['c','llvm'])test('verification ties author requirements and concrete native results to checked source/spec review ('+backend+')',()=>fixture(root=>{
 const before=readFileSync(join(root,'math.aug'),'utf8'),result=invoke(root,'--backend',backend);assert.equal(result.status,0,result.stderr+result.stdout);const report=JSON.parse(result.stdout);
 assert.equal(report.status,'passed');assert.equal(report.compiler.status,'accepted');assert.equal(report.behavior.status,'passed');assert.equal(report.engineerReview,'required');assert.equal(report.generalProof,'not-established');
 assert.match(report.revision,/^[a-f0-9]{64}$/);assert.equal(report.requirements.origin,'author-supplied');assert.equal(report.requirements.independence,'author-declared');assert.match(report.requirements.sha256,/^[a-f0-9]{64}$/);
 assert.deepEqual(report.behavior.results.map(item=>item.id),ids);assert.equal(report.behavior.passed,3);assert.equal(report.behavior.failed,0);assert.equal(report.behavior.backend,backend);
 assert.equal(report.requirements.items[0].status,'passed');assert.equal(report.review.contexts[0].coverage.mandatory,'complete');assert.equal(report.review.contexts[0].behaviorDescriptions,'source-derived');
 assert.match(report.review.specifications.find(spec=>spec.file==='math.aug.md').text,/double/);assert.equal(report.review.specifications.every(spec=>spec.origin==='source-derived'),true);
 assert.equal(readFileSync(join(root,'math.aug'),'utf8'),before);assert.equal(existsSync(join(root,'math.aug.md')),false);assert.match(report.review.specifications.find(spec=>spec.file==='math.aug.md').text,/math\.aug#L1\)/);assert.equal(report.review.specifications.every(spec=>spec.file.endsWith('.aug.md')),true);assert.equal(report.review.sources.find(item=>item.file==='math.aug').text,before);
 writeFileSync(join(root,'math.aug'),good.replace('value * 2','value'));
 const wrong=invoke(root,'--backend',backend);assert.equal(wrong.status,1,wrong.stderr+wrong.stdout);const failure=JSON.parse(wrong.stdout);assert.equal(failure.compiler.status,'accepted');assert.equal(failure.behavior.failed,2);assert.equal(failure.status,'failed');assert.equal(failure.requirements.items[0].status,'failed');
}));

test('missing cases, empty requirements and stale specifications never supply acceptance',()=>fixture(root=>{
 for(const value of [{format:1,requirements:[]},{format:1,requirements:[{id:'same',description:'Check behavior',tests:[]}]},{format:1,requirements:[{id:'same',description:'Check behavior',tests:['missing']}]}]){
  writeFileSync(join(root,'requirements.json'),JSON.stringify(value));const result=invoke(root);assert.equal(result.status,1,result.stderr+result.stdout);assert.equal(existsSync(join(root,'.aug-build/tests')),false);
 }
 writeFileSync(join(root,'generated.aug.md'),'<!-- Generated by aug spec. Edit the August source, then regenerate. -->\n');
 const denied=spawnSync(process.execPath,[cli,'verify',root,'--requirements','generated.aug.md','--json'],{encoding:'utf8'});assert.equal(denied.status,1);assert.match(denied.stderr,/author|requirement/i);
}));

test('compiler rejection remains separate from behavioral evidence and does not run tests',()=>fixture(root=>{
 writeFileSync(join(root,'math.aug'),good.replace('value * 2','"wrong"'));
 const result=invoke(root);assert.equal(result.status,1,result.stderr+result.stdout);const report=JSON.parse(result.stdout);
 assert.equal(report.status,'rejected');assert.equal(report.compiler.status,'rejected');assert.equal(report.behavior.status,'not-run');assert.ok(report.compiler.diagnostics.some(issue=>issue.code==='TYPE'));
 assert.equal(existsSync(join(root,'.aug-build/tests')),false);assert.equal(report.review.sources.find(item=>item.file==='math.aug').text,readFileSync(join(root,'math.aug'),'utf8'));
}));

test('verification options are strict and explain author requirement mapping',()=>fixture(root=>{
 for(const options of [['--write'],['--json'],['--backend','bad'],['--timeout','0'],['--requirements','requirements.json']])assert.equal(invoke(root,...options).status,2);
 const human=spawnSync(process.execPath,[cli,'verify',root,'--requirements','requirements.json','--backend','c'],{encoding:'utf8',timeout:90000});assert.equal(human.status,0,human.stderr+human.stdout);assert.match(human.stdout,/twice/);assert.match(human.stdout,/3 passed/);assert.match(human.stdout,/review/i);
}));

async function runWhileLowering(root,backend,change){
 const child=spawn(process.execPath,[cli,'verify',root,'--requirements','requirements.json','--backend',backend,'--json'],{stdio:['ignore','pipe','pipe']});
 let stdout='',stderr='',closed=false,launchError;child.stdout.on('data',text=>stdout+=text);child.stderr.on('data',text=>stderr+=text);child.on('error',error=>launchError=error);
 const done=new Promise(resolve=>child.once('close',status=>{closed=true;resolve(status);}));
 try{
  let observed=false;const deadline=Date.now()+30000;
  while(!closed&&Date.now()<deadline){if(existsSync(join(root,'.aug-build/tests/test-0.'+(backend==='llvm'?'ll':'c')))){change();observed=true;break;}await new Promise(resolve=>setTimeout(resolve,10));}
  assert.equal(observed,true,'native lowering was not observed: '+(launchError??stderr));const status=await done;
  assert.equal(status,1,stderr+stdout);return JSON.parse(stdout);
 }finally{if(!closed){child.kill('SIGTERM');await done;}}
}
for(const changed of ['source','requirements'])test('verification rejects '+changed+' changes made after native lowering',async()=>{
 const root=mkdtempSync(join(tmpdir(),'aug-verification-stale-'));
 try{
  writeFileSync(join(root,'main.aug'),'import double from math\nprint(value=double(value=4))\n');writeFileSync(join(root,'math.aug'),good);
  writeFileSync(join(root,'requirements.json'),JSON.stringify({format:1,requirements:[{id:'twice',description:'Return twice the input.',tests:ids}]}));
  const report=await runWhileLowering(root,'llvm',()=>{
   if(changed==='source')writeFileSync(join(root,'math.aug'),good+'// Different source revision.\n');
   else writeFileSync(join(root,'requirements.json'),JSON.stringify({format:1,requirements:[{id:'twice',description:'Changed requirement.',tests:ids}]}));
  });
  assert.equal(report.status,'stale');assert.equal(report.freshness.status,'changed');assert.equal(report.behavior.status,'passed');assert.equal(report.behavior.sourceRevision,report.revision);
 }finally{rmSync(root,{recursive:true,force:true});}
});

test('requirement schemas bound selection and reject unreviewed metadata',()=>fixture(root=>{
 for(const requirements of [
  {format:1,requirements:[{id:'x',description:'Check behavior',tests:[ids[0]],expected:'generated'}]},
  {format:1,requirements:[{id:'x',description:'Check behavior',tests:[ids[0],ids[0]]}]},
  {format:1,requirements:[{id:'x',description:'Check behavior',tests:ids},{id:'x',description:'Other',tests:ids}]},
  {format:1,requirements:[{id:'x',description:' ',tests:ids}]},
  {format:1,requirements:[{id:'x',description:'Check behavior',tests:Array.from({length:257},(_,i)=>'test-'+i)}]},
  {format:1,requirements:[{id:'x',description:'Check behavior',tests:ids}],approved:true}
 ]){writeFileSync(join(root,'requirements.json'),JSON.stringify(requirements));const result=invoke(root);assert.equal(result.status,1,result.stderr+result.stdout);assert.equal(existsSync(join(root,'.aug-build/tests')),false);}
}));

test('finite verification retains interface-dispatch boundaries rather than claiming a complete edit graph',()=>fixture(root=>{
 writeFileSync(join(root,'main.aug'),'');
 writeFileSync(join(root,'math.aug'),'interface NumberSource { read() returns int }\nFixed() implements NumberSource { read() { return 7 } }\nsample(NumberSource source) returns int { return source.read() }\ntest sample { when acceptance { it returns_seven { assert(condition=sample(source=Fixed()) == 7) } } }\n');
 writeFileSync(join(root,'requirements.json'),JSON.stringify({format:1,requirements:[{id:'seven',description:'Read the supplied source.',tests:['math.aug:sample:acceptance:returns_seven']}]}));
 const result=invoke(root,'--backend','c');assert.equal(result.status,0,result.stderr+result.stdout);const report=JSON.parse(result.stdout);
 assert.equal(report.review.contexts[0].coverage.graph,'bounded');assert.ok(report.review.contexts[0].boundaries.some(item=>item.kind==='interface-dispatch'));assert.equal(report.generalProof,'not-established');
}));

test('source-library requirement identities and review paths are stable through a linked root',()=>fixture(root=>{
 const library=join(root,'library'),linked=join(root,'linked');mkdirSync(join(library,'src'),{recursive:true});
 writeFileSync(join(library,'aug-package.json'),JSON.stringify({format:1,name:'@test/acceptance',version:'0.1.0',compiler:JSON.parse(readFileSync('package.json','utf8')).version,source:'src',dependencies:{}}));
 writeFileSync(join(library,'src/export.aug'),'export double from math\n');writeFileSync(join(library,'src/math.aug'),good);
 writeFileSync(join(library,'requirements.json'),JSON.stringify({format:1,requirements:[{id:'twice',description:'Return twice the input.',tests:ids.map(id=>'src/'+id)}]}));symlinkSync(library,linked,'dir');
 const result=invoke(linked,'--backend','c');assert.equal(result.status,0,result.stderr+result.stdout);const report=JSON.parse(result.stdout);assert.equal(report.requirements.file,'requirements.json');assert.equal(report.review.sources[0].file,'src/math.aug');
}));

test('native test revision preconditions reject a different loaded program before execution',()=>fixture(root=>{
 const accepted=JSON.parse(invoke(root,'--backend','c').stdout);rmSync(join(root,'.aug-build'),{recursive:true,force:true});
 writeFileSync(join(root,'math.aug'),good.replace('assertEqual(actual=double(value), expected)','print(value="NEW PROGRAM EXECUTED"); assertEqual(actual=double(value), expected)'));
 const result=spawnSync(process.execPath,[cli,'test',root,'--backend','c','--json','--expected-revision',accepted.revision],{encoding:'utf8'});
 assert.equal(result.status,1,result.stderr+result.stdout);const report=JSON.parse(result.stdout);assert.deepEqual(report.tests,[]);assert.notEqual(report.sourceRevision,accepted.revision);assert.match(report.error,/revision|source/i);assert.equal(existsSync(join(root,'.aug-build/tests')),false);
}));

test('ordinary repository-native imports supply real zlib acceptance evidence through LLVM',{skip:process.env.AUG_TEST_PUBLIC!=='1'},()=>fixture(root=>{
 writeFileSync(join(root,'main.aug'),'');
 writeFileSync(join(root,'math.aug'),'import CompressionError and compress and decompress from "https://github.com/GreenPandaStudios/aug-zlib#v0.1.5"\nroundTrip() returns Bytes unless CompressionError { Bytes input = "The world runs on language".bytes(); Bytes compressed = compress(input); return decompress(input=compressed, maximumOutput=4096) }\ntest roundTrip { when compression { it preserves_bytes { Bytes restored = roundTrip(); assert(restored.text() == "The world runs on language"); assert(restored.length() == 26) } } }\n');
 writeFileSync(join(root,'requirements.json'),JSON.stringify({format:1,requirements:[{id:'real-zlib',description:'Restore the original 26 UTF-8 bytes.',tests:['math.aug:roundTrip:compression:preserves_bytes']}]}));
 const result=invoke(root,'--backend','llvm');assert.equal(result.status,0,result.stderr+result.stdout);const report=JSON.parse(result.stdout);
 assert.equal(report.behavior.passed,1);assert.ok(report.review.contexts[0].boundaries.some(item=>item.kind==='native-code'));assert.equal(report.source.configuration.find(item=>item.file==='aug.lock.json').sha256!==null,true);assert.equal(report.requirements.items[0].status,'passed');
}));

test('metadata rejected after execution cannot pass with an unchanged source revision',async()=>{
 const root=realpathSync(mkdtempSync(join(tmpdir(),'aug-verification-metadata-')));
 try{
  mkdirSync(join(root,'src'));writeFileSync(join(root,'src/export.aug'),'export double from math\n');writeFileSync(join(root,'src/math.aug'),good);
  const bytes=JSON.stringify({format:1,profile:'aug-native-abi-1',resources:[],functions:[]});writeFileSync(join(root,'native.abi.json'),bytes);
  const library='lib/fake'+(process.platform==='darwin'?'.dylib':'.so');
  writeFileSync(join(root,'aug-package.json'),JSON.stringify({format:2,name:'@test/metadata',version:'0.1.0',compiler:JSON.parse(readFileSync('package.json','utf8')).version,source:'src',dependencies:{},native:{profile:'aug-native-abi-1',bindings:'native.abi.json',bindingsSha256:createHash('sha256').update(bytes).digest('hex'),upstream:{repository:'https://example.invalid/native',version:'1.0.0',sourceRevision:'a'.repeat(40)},artifacts:[{id:'host',target:nativeHostTarget(),url:'https://example.invalid/native.tgz',sha256:'b'.repeat(64),maximumDownloadBytes:4096,maximumUnpackedBytes:8192,link:{kind:'dynamic',libraries:[library]},runtime:{files:[library],relocation:'loader-relative'},components:[{id:'native',version:'1.0.0',compatibilityKey:'native',linkage:'dynamic',required:true}],fileManifest:'files.json',provenance:'provenance.json',notices:'THIRD_PARTY_NOTICES.md'}]}}));
  writeFileSync(join(root,'requirements.json'),JSON.stringify({format:1,requirements:[{id:'twice',description:'Return twice the input.',tests:ids.map(id=>'src/'+id)}]}));
  const report=await runWhileLowering(root,'c',()=>writeFileSync(join(root,'native.abi.json'),bytes+'\n'));
  assert.equal(report.status,'stale');assert.equal(report.behavior.status,'passed');assert.equal(report.freshness.status,'changed');assert.equal(report.freshness.afterRevision,report.revision);assert.ok(report.freshness.diagnostics.some(issue=>/NATIVE_INTEGRITY/.test(issue.message)));
 }finally{rmSync(root,{recursive:true,force:true});}
});
