// Generated by aug spec. This is a copy of the installed dependency source.
// aug-spec: "contracts.aug.md" explains this file. Read it before changes; refresh with aug spec.
GpuError(int code, string message) implements Error:
    explain() returns string:
        return message
