# syntax=docker/dockerfile:1
FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates zlib1g \
    && rm -rf /var/lib/apt/lists/*
RUN groupadd --system august && useradd --system --gid august --home-dir /app august
WORKDIR /app
USER august
ENTRYPOINT ["/app/program"]
