// Generated by aug spec. This is a copy of the installed dependency source.
// aug-spec: "bindings.aug.md" explains this file. Read it before changes; refresh with aug spec.
extern C resource Device
extern C resource Buffer
