import {cpSync, existsSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync} from 'node:fs';
import {basename, dirname, join, relative, resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {loadProject} from '../src/project.ts';
import {checkProject} from '../src/checker.ts';
import {loadConfig} from '../src/config.ts';
import {installPackages, packageSpecifications} from '../src/package-manager.ts';
import {formatFile} from '../src/formatter.ts';
import {parse} from '../src/parser.ts';
import {generateSpecs, updateSpecs} from '../src/spec.ts';
import {checkUnitTests, discoverTests, mergeTestAnalysis} from '../src/testing.ts';
import {projectArchive} from './doc-downloads.mjs';

const root=resolve(import.meta.dirname,'..');
export const examples=JSON.parse(readFileSync(join(root,'docs/example-projects.json'),'utf8'));
const slash=path=>path.replaceAll('\\','/');
const url=path=>slash(path).split('/').map(encodeURIComponent).join('/');
const compare=(a,b)=>a<b?-1:a>b?1:0;
const safeAnchor=id=>id.replace(/[^A-Za-z0-9_.-]/g,char=>'-'+char.codePointAt(0).toString(16)+'-');
const frontmatter=(title,source,dependency=false,exampleFile=false)=>`---\ntitle: ${JSON.stringify(title)}\ngenerated: true\nsource: ${JSON.stringify(source)}\neditLink: false\nprev: false\nnext: false\noutline: [2, 3]\n${dependency?'search: false\n':''}${exampleFile?'pageClass: aug-example-page\n':''}---\n\n`;
const code=text=>`\`${text}\``;
const fence=(source,language='aug',label='')=>{
  const delimiter='`'.repeat(Math.max(3,1+Math.max(0,...(source.match(/`+/g)??[]).map(part=>part.length))));
  return `${delimiter}${language}${label?' ['+label+']':''}\n${source.trimEnd()}\n${delimiter}\n`;
};
const slug=example=>example.path.replace(/^(examples|benchmarks)\//,'').replaceAll('/','-')+(example.path.startsWith('benchmarks/')?'-benchmark':'');
export const exampleDirectory=example=>'docs/examples/'+slug(example);
export const exampleDownload=example=>'docs/public/downloads/'+slug(example)+'.zip';
const npmAug='aug';
const downloadFiles=directory=>readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{
  if(entry.name.startsWith('.')&&entry.name!=='.aug-spec'||['node_modules','dist'].includes(entry.name))return [];
  const file=join(directory,entry.name);
  if(entry.isDirectory())return downloadFiles(file);
  return /(?:\.aug(?:\.md)?|\.yaml|\.json|\.c|\.h|\.http)$/.test(entry.name)||['AGENTS.md','README.md'].includes(entry.name)?[file]:[];
});

function checkedProject(project) {
  const checked=checkProject(project), discovery=discoverTests(project), tests=checkUnitTests(project,discovery.tests);
  checked.diagnostics.push(...discovery.diagnostics,...tests.flatMap(test=>test.checked.diagnostics));
  mergeTestAnalysis(checked,tests);
  const errors=checked.diagnostics.filter(issue=>issue.severity!=='warning');
  if(errors.length)throw new Error('Invalid example: '+JSON.stringify(errors));
  return checked;
}

/** Work in a temporary copy, including offline local package installation. Source files stay untouched. */
export function withExampleProject(example, action, overrides) {
  const temporary=realpathSync(mkdtempSync(join(tmpdir(),'aug-wiki-example-')));
  try {
    const source=join(root,example.path), packages=example.path.startsWith('examples/packages/');
    const origin=packages?join(root,'examples/packages'):source;
    const destination=join(temporary,packages?'packages':'project');
    cpSync(origin,destination,{recursive:true,filter:path=>{
      if(path===origin)return true;
      const name=basename(path);
      return !name.startsWith('.')&&!['node_modules','dist'].includes(name)&&!name.endsWith('.aug.md')&&!/\.(?:tgz|tar\.gz)$/.test(name);
    }});
    const directory=packages?join(destination,basename(source)):destination;
    if(Object.keys(packageSpecifications(directory,loadConfig(directory).config.packages)).length)installPackages(directory,existsSync(join(directory,'aug.lock.json')),false);
    const project=loadProject(directory,overrides), checked=checkedProject(project);
    return action({project,checked,directory,source});
  } finally {rmSync(temporary,{recursive:true,force:true});}
}

/** Build source views with the real formatter and explanations with the real spec compiler. */
export function buildExamplePages(overrides) {
  const outputs=new Map();
  const add=(path,text)=>{
    if(!/^(?:docs\/examples|docs\/public\/downloads|examples|benchmarks)\//.test(path)||relative(root,resolve(root,path)).startsWith('..'))
      throw new Error('Generated example artifact escapes its repository folder: '+path);
    if(outputs.has(path))throw new Error('Duplicate example page: '+path);
    if(path.endsWith('.aug.md')&&existsSync(join(root,path))&&!readFileSync(join(root,path),'utf8').startsWith('<!-- Generated by aug spec.'))
      throw new Error('Refusing to replace handwritten specification: '+path);
    outputs.set(path,text);
  };
  for(const example of examples)withExampleProject(example,({project,checked,directory,source})=>{
    updateSpecs(checked);
    const artifacts=generateSpecs(checked);
    for(const output of artifacts)add(slash(relative(root,join(source,relative(directory,output.path)))),output.text);
    add(slash(relative(root,join(source,'.aug-spec/manifest.json'))),readFileSync(join(directory,'.aug-spec/manifest.json'),'utf8'));
    const base=exampleDirectory(example), home=join(base,'index.md');
    const files=[...project.files.values()].filter(file=>!file.builtin&&!file.package).sort((a,b)=>
      Number(basename(b.path)==='main.aug')-Number(basename(a.path)==='main.aug')||compare(relative(directory,a.path),relative(directory,b.path)));
    const docs=new Map(), sources=new Map();
    for(const output of artifacts.filter(output=>output.path.endsWith('.aug.md'))) {
      const name=slash(relative(directory,output.path));
      const page=join(base,name.replace(/^\.aug-spec\//,'dependencies/').replace(/\.aug\.md$/,'.md'));
      docs.set(output.path,page);sources.set(output.path.slice(0,-3),page);
    }
    const nav=files.map(file=>`- [${code(slash(relative(directory,file.path)))}](${url(relative(dirname(home),sources.get(file.path)))})`).join('\n');
    let overview=frontmatter(example.title,example.path)+`# ${example.title}\n\n${example.description}\n\n`+
      'Open a file to read its source beside the explanation produced by `aug spec`. **Indentation** and **Braces** display the same checked program; your choice carries across file pages.\n\n';
    if(example.walkthrough?.length) {
      overview+='## Follow the program\n\n';
      for(const step of example.walkthrough) {
        const file=files.find(file=>slash(relative(directory,file.path))===step.file);
        if(!file)throw new Error(example.path+': walkthrough refers to missing file '+step.file);
        overview+=`Read [${code(step.file)}](${url(relative(dirname(home),sources.get(file.path)))}). ${step.explanation}\n\n`;
      }
    }
    overview+=`## Project files\n\n${nav}\n\n`;
    const auxiliary=['main.yaml','aug-package.json','package.json'].filter(name=>existsSync(join(source,name)));
    for(const name of auxiliary) {
      const page=join(base,name.replaceAll('.','-')+'.md');
      overview+=`- [${code(name)}](${url(relative(dirname(home),page))})\n`;
      add(page,frontmatter(name+' · '+example.title,example.path+'/'+name)+`# ${code(name)}\n\n[${example.title}](index.md) · Project configuration\n\n`+fence(readFileSync(join(source,name),'utf8'),name.endsWith('.yaml')?'yaml':'json'));
    }
    const packagePair=example.path.startsWith('examples/packages/');
    const downloadRoot=packagePair?dirname(directory):directory;
    const workingDirectory=slug(example)+(packagePair?'/'+basename(directory):'');
    let commands=`cd ${workingDirectory}\n`;
    if(example.path==='examples/packages/app')commands+=`${npmAug} install . --offline\n`;
    commands+=`${npmAug} check .\n${npmAug} spec .\n`;
    if(project.library)commands+=`${npmAug} test .\n${npmAug} pack .\n`;
    else commands+=(files.some(file=>file.items.some(item=>item.kind==='test'))?`${npmAug} test .\n`:'')+`${npmAug} run .\n`;
    overview+='\n## Try this project\n\n'+
      `[Download this project](/downloads/${slug(example)}.zip), then extract the archive in an empty working folder. It contains the checked source, configuration, and generated specs.`+
      (packagePair?' Both the application and its neighboring arithmetic library are included.':'')+
      ' [Install August](../../getting-started.md) once, then run these commands. Native libraries are prepared automatically when needed:\n\n'+fence(commands,'sh')+'\n';
    const archiveFiles=new Map(downloadFiles(downloadRoot).map(file=>[slug(example)+'/'+slash(relative(downloadRoot,file)),readFileSync(file)]));
    archiveFiles.set(slug(example)+'/LICENSE',readFileSync(join(root,'LICENSE')));
    archiveFiles.set(slug(example)+'/README.md',`# ${example.title}\n\n${example.description}\n\nInstall August as described at https://greenpandastudios.github.io/augscript/getting-started. Native commands prepare required libraries automatically.\n\nFrom the folder containing this extracted project:\n\n${fence(commands,'sh')}\nRead the source beside its compiled specification at https://greenpandastudios.github.io/augscript/examples/${slug(example)}/.\n`);
    add(exampleDownload(example),projectArchive(archiveFiles));
    if(example.path==='examples/oidc-login')overview+='Open `http://127.0.0.1:8787` and sign in with **ada** / **august-demo**. This development example keeps accounts, signing keys, and sessions in process memory. See [web and crypto](../../web.md) and [the remaining library gaps](../../web-library-gaps.md).\n\n';
    if(example.group==='Measured programs')overview+='See [the performance page](../../performance.md) for measurements, input sizes, and reproduction steps.\n\n';
    overview+='[Browse all examples](../index.md)\n';
    add(home,overview);
    for(const artifact of artifacts.filter(output=>output.path.endsWith('.aug.md'))) {
      const page=docs.get(artifact.path), local=relative(directory,artifact.path), dependency=local.startsWith('.aug-spec/');
      const copy=artifact.path.slice(0,-3), identity=slash(relative(directory,copy));
      const displayName=dependency?identity.replace(/^\.aug-spec\//,''):identity;
      const file=project.files.get(artifact.source);
      if(!file)throw new Error('Cannot find source for '+identity);
      const hinted=artifacts.find(output=>output.kind==='source-hint'&&output.source===file.path);
      const displayed=hinted?parse(file.path,hinted.text).file:file;
      const formats=['indent','braces'].map(style=>formatFile({...project,config:{...project.config,block_style:style,indentation:'spaces'}},displayed));
      let text=artifact.text.replace(/^<!--[^\n]*-->\n\n# [^\n]+\n\n/,'');
      text=text.replace(/<a id="([^"]+)"><\/a>\n+(#{2,6} [^\n]+)/g,(_,id,heading)=>heading+' {#'+safeAnchor(id)+'}');
      // Promote source links to the readable code on the same wiki; keep exact declaration anchors.
      text=text.replace(/\]\(([^\n)]+)\)/g,(original,href)=>{
        if(/^(?:https?:|mailto:|#)/.test(href))return original;
        const [path,anchor]=href.split('#');
        const target=resolve(dirname(artifact.path),decodeURIComponent(path)), destination=docs.get(target)??sources.get(target);
        if(!destination)throw new Error('Unmapped specification link: '+href+' in '+identity);
        return ']('+url(relative(dirname(page),destination))+(sources.has(target)?'#code':anchor?'#'+safeAnchor(decodeURIComponent(anchor)):'')+')';
      });
      text=text.replace(/^(#{2,5}) /gm,'$1# ');
      const siblings=files.map(file=>`- [${code(slash(relative(directory,file.path)))}](${url(relative(dirname(page),sources.get(file.path)))})`).join('\n');
      add(page,frontmatter(displayName+' · '+example.title,example.path+'/'+identity,dependency,true)+`# ${code(displayName)}\n\n`+
        `[${example.title}](${url(relative(dirname(page),home))}) · ${dependency?'Dependency source and specification':'Source and specification'}\n\n`+
        (dependency?'This is the exact dependency version used by this example.\n\n':`::: details Files in this project\n\n${siblings}\n\n:::\n\n`)+
        '::::: example-compare\n\n:::: example-code\n\n## Code {#code}\n\n::: code-group\n\n'+fence(formats[0],'aug','Indentation')+'\n'+fence(formats[1],'aug','Braces')+'\n:::\n\n::::\n\n'+
        ':::: example-spec\n\n## Compiled specification {#specification}\n\n'+text+'\n::::\n\n:::::\n');
    }
  },overrides);
  let index=frontmatter('Example projects','examples and benchmarks')+'# Example projects\n\n'+
    'Read a complete program, follow its dependencies, and compare the source with its compiled explanation. Every file has highlighted **Indentation** and **Braces** views and the actual output of `aug spec`. Dependency links open the exact version used by the project. Each project has a download you can run with the published npm CLI.\n\n'+
    'Start with [Hello world with dependencies](hello/index.md) to trace a greeting through two folder boundaries. Then [review a change to the tested calculator](../guides/change-a-module.md). For a larger application, the [OpenID Connect example](oidc-login/index.md) combines pages, provider and client endpoints, and a session JWT. It is a development demonstration with documented limits.\n\n'+
    'If you are learning the language for the first time, use [the book](../learn/index.md). The gallery is for exploring whole projects and looking at the code behind a specific feature or measurement.\n\n';
  for(const group of new Set(examples.map(example=>example.group))) {
    index+='## '+group+'\n\n| Project | What it demonstrates |\n| --- | --- |\n';
    for(const example of examples.filter(example=>example.group===group))index+=`| [${example.title}](${url(relative('docs/examples',join(exampleDirectory(example),'index.md')))}) | ${example.description.replaceAll('|','\\|')} |\n`;
    index+='\n';
  }
  add('docs/examples/index.md',index.trimEnd()+'\n');
  return outputs;
}
