import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {loadProject} from '../src/project.ts';
import {checkProject} from '../src/checker.ts';
import {generateSpecs} from '../src/spec.ts';
import {formatFile} from '../src/formatter.ts';

/** The front-page explanation and measurements come from the checked program. */
export function homepageExample(root) {
  const directory=join(root,'benchmarks/greetings');
  const checked=checkProject(loadProject(directory));
  assert.deepEqual(checked.diagnostics.filter(issue=>issue.severity!=='warning'),[]);
  const file=checked.project.files.get(join(directory,'main.aug'));
  const source=style=>formatFile({...checked.project,config:{...checked.project.config,block_style:style,indentation:'spaces',assignment:'equals'}},file)
    .replace(/^\/\/ aug-spec:.*\n/,'').trim();
  const spec=generateSpecs(checked,{manifest:false}).find(output=>output.path===file.path+'.md').text;
  const paragraph=spec.split('## Startup\n\n')[1].split('\n\nBuilt-in operations')[0];
  assert.ok(paragraph.startsWith('It sets `greetings`'));
  const report=JSON.parse(readFileSync(join(root,'docs/greeting-results.json'),'utf8'));
  assert.equal(report.status,'passed');
  assert.equal(report.sources.august,file.source,'Benchmark source differs from the homepage program');
  assert.equal(report.sources.c,readFileSync(join(root,'benchmarks/greetings.c'),'utf8'));
  assert.ok(report.methodology.iterations>=30,'Publish at least thirty measured runs');
  const time=name=>report.results.find(row=>row.implementation===name).milliseconds.median.toFixed(2);
  return `[homepage-generated]: #

::::: example-compare
:::: example-code
### This is August

Print a greeting one million times. Choose the block style you prefer; both programs mean the same thing.

::: code-group

\`\`\`aug [Indentation]
${source('indent')}
\`\`\`

\`\`\`aug [Braces]
${source('braces')}
\`\`\`

:::

::::

:::: example-spec
### This is its compiled specification

**Generated by \`aug spec\` from the program beside it.**

${paragraph}

Specs sit beside each source file as \`.aug.md\`. Read one to review an unfamiliar module, follow its dependency links, or give a coding agent checked context before an edit. Regenerate it when the code changes.

[Explore a complete project with its specs](examples/hello/index.md) · [Use compiled specifications](specifications.md)
::::

:::::

### Native performance, compared with C

This program writes **1,000,000 greetings: 20 MB of UTF-8 text**. The output below is abbreviated:

\`\`\`text
Hello, August! 👋
Hello, August! 👋
… 1,000,000 lines in total
\`\`\`

The equivalent C program performs the same work and flushes each line, as August does:

::: details Show the C program

\`\`\`c
${report.sources.c.trim()}
\`\`\`

:::

::: benchmark-chart greetings
:::

On ${report.cpu}, August takes **${time('August')} ms** and C takes **${time('C')} ms** (median of ${report.methodology.iterations} runs after ${report.methodology.warmup} warmups). Both use release optimization and write to a regular file; every run's complete output is checked. This measures printing and file I/O, including process startup. It does not measure string concatenation.

August runs close to C in this example. The [full performance section](performance.md) compares integer loops, collections, JSON, application kernels, and HTTP, including workloads where August has more overhead. Use those programs as starting points, then measure your own application.

[Read the source and spec](examples/greetings-benchmark/main.md) · [Inspect every sample and the environment](greeting-results.json)
`;
}
