import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {loadProject} from '../src/project.ts';
import {checkProject} from '../src/checker.ts';
import {generateSpecs} from '../src/spec.ts';
import {formatFile} from '../src/formatter.ts';
import {rebaseReading} from '../src/spec-reading.ts';

/** The front-page explanation and measurements come from the checked program. */
export function homepageBenchmark(root) {
  const directory=join(root,'benchmarks/greetings');
  const checked=checkProject(loadProject(directory));
  assert.deepEqual(checked.diagnostics.filter(issue=>issue.severity!=='warning'),[]);
  const file=checked.project.files.get(join(directory,'main.aug'));
  const source=style=>formatFile({...checked.project,config:{...checked.project.config,block_style:style,indentation:'spaces',assignment:'equals'}},file)
    .replace(/^\/\/ aug-spec:.*\n/,'').trim();
  const spec=generateSpecs(checked,{manifest:false}).find(output=>output.path===file.path+'.md').text;
  const paragraph=spec.split('## Startup\n\n')[1].split('\n\nBuilt-in operations')[0]
    .replace(/\[source\]\(main\.aug#[^)]+\)/g,'[source](examples/greetings-benchmark/main.md#code)');
  assert.ok(paragraph.startsWith('It sets `greetings`'));
  const report=JSON.parse(readFileSync(join(root,'docs/greeting-results.json'),'utf8'));
  assert.equal(report.status,'passed');
  assert.equal(report.sources.august,file.source,'Benchmark source differs from the homepage program');
  assert.equal(report.sources.c,readFileSync(join(root,'benchmarks/greetings.c'),'utf8'));
  assert.ok(report.methodology.iterations>=30,'Publish at least thirty measured runs');
  const time=name=>report.results.find(row=>row.implementation===name).milliseconds.median.toFixed(2);
  return `[homepage-generated]: #

::::: example-compare
:::: example-code
### This is August

This program prints a greeting one million times. Indentation and braces are two ways to write the same loop.

::: code-group

\`\`\`aug [Indentation]
${source('indent')}
\`\`\`

\`\`\`aug [Braces]
${source('braces')}
\`\`\`

:::

::::

:::: example-spec
### This is its compiled specification

**Generated by \`aug spec\` from the program beside it.**

${paragraph}

The spec is saved beside the source as \`main.aug.md\`. Read it to understand the loop, or give it to a coding agent before an edit. Larger modules include links to the dependencies they use.

[Explore a complete project with its specs](examples/hello/index.md) · [Use compiled specifications](specifications.md)
::::

:::::

### Native performance, compared with C

This program writes **1,000,000 greetings: 20 MB of UTF-8 text**. The output below is abbreviated:

\`\`\`text
Hello, August! 👋
Hello, August! 👋
… 1,000,000 lines in total
\`\`\`

The equivalent C program performs the same work and flushes each line, as August does:

::: details Show the C program

\`\`\`c
${report.sources.c.trim()}
\`\`\`

:::

::: benchmark-chart greetings
:::

August ${report.compiler} on ${report.cpu} takes **${time('August')} ms** and C takes **${time('C')} ms** (median of ${report.methodology.iterations} runs after ${report.methodology.warmup} warmups). Both programs use release optimization, write to a file, and flush each line. Every run must produce the same 20 MB output. The times include process startup and file I/O.

The [performance reports](performance.md) compare more programs: integer loops, collections, JSON, and HTTP. Results vary by workload; use the sources to build a comparison for your own application.

[Read the source and spec](examples/greetings-benchmark/main.md) · [Inspect every sample and the environment](greeting-results.json)
`;
}

/** A single checked project supplies the welcome code, prose and diagrams. */
export function homepageExample(root,pages) {
  const directory=join(root,'examples/hello'),checked=checkProject(loadProject(directory));
  assert.deepEqual(checked.diagnostics.filter(issue=>issue.severity!=='warning'),[]);
  const file=checked.project.files.get(join(directory,'app/greeter.aug'));
  const source=style=>formatFile({...checked.project,config:{...checked.project.config,block_style:style,indentation:'spaces',assignment:'equals'}},file)
    .replace(/^\/\/ aug-spec:.*\n/,'').replace(/\/\*\*[\s\S]*?\*\/\s*/g,'').trim();
  const page='docs/examples/hello/app/greeter.md',text=pages.get(page);
  assert.ok(text,'Missing checked welcome example');
  const begin=text.indexOf('### `Greeter`'),end=text.indexOf('### `IGreeter`',begin);
  assert.ok(begin>=0&&end>begin,'Missing greeting specification');
  const spec=rebaseReading(text.slice(begin,end).trim(),join(root,page),join(root,'docs/index.md'))
    .replace(/::: spec-paragraph [^\n]+\n([\s\S]*?)\n:::/g,'$1');
  return '[homepage-generated]: #\n\n## This is August\n\nA greeting is small enough to read in full. The same compiler that checks this code also writes its explanation and diagrams.\n\n'+
    '::::: example-compare\n:::: example-code\n### Readable code\n\nThis component belongs to the [complete greeting project](examples/hello/index.md). Its logger comes from the application’s bindings.\n\n::: code-group\n\n'+
    '```aug [Indentation]\n'+source('indent')+'\n```\n\n```aug [Braces]\n'+source('braces')+'\n```\n\n:::\n::::\n\n:::: example-spec\n### Its compiled specification\n\n**This text is generated from that component by `aug spec`.** The compiler follows the calls and links the dependency contracts. Author comments supply the description of its purpose.\n\n'+spec+
    '\n\n[Read the full explanation](examples/hello/app/greeter.md#specification)\n::::\n:::::\n\nThe application resolves `Greeter` and calls `greet(name="AugScript")`. The configured logger prints:\n\n```text\nHello, AugScript!\n```\n';
}

export function homepageDiagrams(root,pages) {
  const project=pages.get('docs/examples/hello/diagrams/index.md'),operation=pages.get('docs/examples/hello/app/greeter-diagrams.md');
  const overview=project?.match(/```mermaid\n[\s\S]*?\n```/)?.[0];
  const sequence=operation?.slice(operation.indexOf('### Greeter.greet')).match(/```mermaid\n[\s\S]*?\n```/)?.[0];
  assert.ok(overview&&sequence,'Missing checked welcome diagrams');
  return '## The same program, at two resolutions\n\n### Where the greeting goes\n\n'+overview+
    '\n\nThis is the greeting project’s folder view. Startup calls the application; the application calls the logger. Each connection opens its exact inputs and call sites in the [project overview](examples/hello/diagrams/index.md).\n\n### What one operation does\n\n'+sequence+
    '\n\nThis is the generated sequence for `Greeter.greet`. It passes the greeting to the `Logger` contract. The application chooses `ConsoleLogger` in its [startup specification](examples/hello/main.md#specification). Interface dispatch remains visible; the diagram does not guess which instance a caller will use.\n\n'+
    '[Open this operation](examples/hello/app/greeter-diagrams.md#sequence-Greeter.greet) · [Follow its logger](examples/hello/logging/console-diagrams.md#sequence-ConsoleLogger.log) · [Learn to navigate the views](guides/understand-a-project.md)\n';
}
