import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {loadProject} from '../src/project.ts';
import {checkProject} from '../src/checker.ts';
import {generateSpecs} from '../src/spec.ts';
import {formatFile} from '../src/formatter.ts';

/** The front-page explanation and measurements come from the checked program. */
export function homepageExample(root) {
  const directory=join(root,'benchmarks/greetings');
  const checked=checkProject(loadProject(directory));
  assert.deepEqual(checked.diagnostics.filter(issue=>issue.severity!=='warning'),[]);
  const file=checked.project.files.get(join(directory,'main.aug'));
  const source=style=>formatFile({...checked.project,config:{...checked.project.config,block_style:style,indentation:'spaces',assignment:'equals'}},file)
    .replace(/^\/\/ aug-spec:.*\n/,'').trim();
  const spec=generateSpecs(checked,{manifest:false}).find(output=>output.path===file.path+'.md').text;
  const paragraph=spec.split('## Startup\n\n')[1].split('\n\nBuilt-in operations')[0]
    .replace(/\[source\]\(main\.aug#[^)]+\)/g,'[source](examples/greetings-benchmark/main.md#code)');
  assert.ok(paragraph.startsWith('It sets `greetings`'));
  const report=JSON.parse(readFileSync(join(root,'docs/greeting-results.json'),'utf8'));
  assert.equal(report.status,'passed');
  assert.equal(report.sources.august,file.source,'Benchmark source differs from the homepage program');
  assert.equal(report.sources.c,readFileSync(join(root,'benchmarks/greetings.c'),'utf8'));
  assert.ok(report.methodology.iterations>=30,'Publish at least thirty measured runs');
  const time=name=>report.results.find(row=>row.implementation===name).milliseconds.median.toFixed(2);
  return `[homepage-generated]: #

::::: example-compare
:::: example-code
### This is August

This program prints a greeting one million times. Indentation and braces are two ways to write the same loop.

::: code-group

\`\`\`aug [Indentation]
${source('indent')}
\`\`\`

\`\`\`aug [Braces]
${source('braces')}
\`\`\`

:::

::::

:::: example-spec
### This is its compiled specification

**Generated by \`aug spec\` from the program beside it.**

${paragraph}

The spec is saved beside the source as \`main.aug.md\`. Read it to understand the loop, or give it to a coding agent before an edit. Larger modules include links to the dependencies they use.

[Explore a complete project with its specs](examples/hello/index.md) · [Use compiled specifications](specifications.md)
::::

:::::

### Native performance, compared with C

This program writes **1,000,000 greetings: 20 MB of UTF-8 text**. The output below is abbreviated:

\`\`\`text
Hello, August! 👋
Hello, August! 👋
… 1,000,000 lines in total
\`\`\`

The equivalent C program performs the same work and flushes each line, as August does:

::: details Show the C program

\`\`\`c
${report.sources.c.trim()}
\`\`\`

:::

::: benchmark-chart greetings
:::

August ${report.compiler} on ${report.cpu} takes **${time('August')} ms** and C takes **${time('C')} ms** (median of ${report.methodology.iterations} runs after ${report.methodology.warmup} warmups). Both programs use release optimization, write to a file, and flush each line. Every run must produce the same 20 MB output. The times include process startup and file I/O.

The [performance reports](performance.md) compare more programs: integer loops, collections, JSON, and HTTP. Results vary by workload; use the sources to build a comparison for your own application.

[Read the source and spec](examples/greetings-benchmark/main.md) · [Inspect every sample and the environment](greeting-results.json)
`;
}
