import {createHash} from 'node:crypto';
import {httpPolicyNames,httpPolicyNativeName} from './http-policies.ts';

/** Compiler-private identifiers, checked against the compiled target headers. */
export const runtimeOperations=['PRINT','BINARY','UNARY','FIELD','SET_FIELD','LIST','TUPLE','SET','MAP','MAP_SET','LIST_LENGTH','LIST_GET','LIST_AT','LIST_APPEND','TUPLE_LENGTH','TUPLE_GET','SET_LENGTH','SET_ADD','SET_CONTAINS','MAP_LENGTH','MAP_GET','MAP_TAKE','MAP_CONTAINS','STRING_LENGTH','STRING_BYTES','STRING_SPLIT','STRING_STARTS_WITH','STRING_IS_TOKEN','BYTES_LENGTH','BYTES_TEXT','BYTES_BASE64URL','BASE64URL_DECODE','C_INT','READ_FILE','WRITE_FILE','ARGUMENTS','FREEZE','ITER','MAP_ITER','IS_TYPE','SHARED','SHARED_LOCK','JSON_WRAP','JSON_PARSE','JSON_STRINGIFY','JSON_GET','JSON_REQUIRE','JSON_STRING','JSON_INTEGER','JSON_BOOLEAN','JSON_ITEMS','TIME_NOW','EXIT','TEST_CASE','STRING_UTF16_LENGTH','STRING_IS_DECIMAL','STRING_COMPARE_DECIMAL','BYTES_SLICE','BYTES_HEX','FLOAT_IS_FINITE','FLOAT_FLOAT32','JSON_HAS','JSON_PARSE_COMPATIBLE','STRING_TRIM','TEXT','LIST_JOIN','STRING_ENDS_WITH','STRING_REPLACE','STRING_CODE_POINT_LENGTH','STRING_PARSE_INTEGER','STRING_PARSE_FLOAT','STRING_COMPARE'] as const;
export const httpOperations=['HTTP_HEADERS','HTTP_HEADERS_WITH','HTTP_HEADERS_GET','HTTP_HEADERS_ALL','HTTP_RESPONSE','HTTP_RESPONSE_STATUS','HTTP_FINISH','HTTP_EVENT','HTTP_YIELD','HTTP_CLIENT_REQUEST','HTTP_ACTION','HTTP_BODY'] as const;
/** Every private operation declares either a fixed or a collection arity. */
export const runtimeArities:Record<typeof runtimeOperations[number]|typeof httpOperations[number],number|'variadic'>={
  PRINT:1,BINARY:2,UNARY:1,FIELD:1,SET_FIELD:2,LIST:'variadic',TUPLE:'variadic',SET:'variadic',MAP:0,MAP_SET:3,
  LIST_LENGTH:1,LIST_GET:2,LIST_AT:2,LIST_APPEND:2,TUPLE_LENGTH:1,TUPLE_GET:2,SET_LENGTH:1,SET_ADD:2,SET_CONTAINS:2,
  MAP_LENGTH:1,MAP_GET:2,MAP_TAKE:2,MAP_CONTAINS:2,STRING_LENGTH:1,STRING_BYTES:1,STRING_SPLIT:2,STRING_STARTS_WITH:2,STRING_IS_TOKEN:3,
  BYTES_LENGTH:1,BYTES_TEXT:1,LIST_JOIN:2,STRING_ENDS_WITH:2,STRING_REPLACE:3,STRING_CODE_POINT_LENGTH:1,STRING_PARSE_INTEGER:1,STRING_PARSE_FLOAT:1,STRING_COMPARE:2,BYTES_BASE64URL:1,BASE64URL_DECODE:1,C_INT:1,READ_FILE:1,WRITE_FILE:2,ARGUMENTS:0,FREEZE:1,ITER:1,MAP_ITER:1,IS_TYPE:1,
  SHARED:1,SHARED_LOCK:1,JSON_WRAP:1,JSON_PARSE:1,JSON_STRINGIFY:1,JSON_GET:2,JSON_REQUIRE:2,JSON_STRING:1,JSON_INTEGER:1,JSON_BOOLEAN:1,JSON_ITEMS:1,
  TIME_NOW:0,EXIT:1,TEST_CASE:0,HTTP_HEADERS:0,HTTP_HEADERS_WITH:3,HTTP_HEADERS_GET:2,HTTP_HEADERS_ALL:2,HTTP_RESPONSE:3,HTTP_RESPONSE_STATUS:2,
  HTTP_FINISH:1,HTTP_EVENT:4,HTTP_YIELD:1,HTTP_CLIENT_REQUEST:5,HTTP_ACTION:'variadic',HTTP_BODY:1,STRING_UTF16_LENGTH:1,STRING_IS_DECIMAL:1,STRING_COMPARE_DECIMAL:2,BYTES_SLICE:3,BYTES_HEX:1,FLOAT_IS_FINITE:1,FLOAT_FLOAT32:1,JSON_HAS:2,JSON_PARSE_COMPATIBLE:1,STRING_TRIM:1,TEXT:1,
};
export const schemaKinds=['INT','C_INT','FLOAT','BOOL','STRING','LIST','MAP','SET','TUPLE','RECORD','JSON'] as const;
export const runtimeIdentifiers=Object.fromEntries([
  ...runtimeOperations.map((name,index)=>['AUG_IR_'+name,index+1]),
  ...httpOperations.map((name,index)=>['AUG_IR_'+name,index+1]),
  ...schemaKinds.map((name,index)=>['AUG_SCHEMA_'+name,index]),
  ...httpPolicyNames.map((name,index)=>[httpPolicyNativeName(name),index+1]),
]);
export const runtimeIdentifierSha256=createHash('sha256').update(JSON.stringify(runtimeIdentifiers)).digest('hex');
