import { createHash } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative, resolve } from 'node:path';
import type { BindDecl, ClassDecl, Expr, GenericHeader, MethodDecl, Param, SourceFile, Span, Stmt, TestDecl, TopLevel, TypeRef } from './ast.ts';
import { fieldsOf, typeName } from './ast.ts';
import { builtinFunctions, builtinProperties, builtinTypes, collectionOperations, operationType, type BuiltinOperation } from './builtins.ts';
import type { CheckedProject } from './checker.ts';
import { callableDocumentation } from './documentation.ts';
import { javadocBefore, type Javadoc } from './javadoc.ts';
import { libraryChild, libraryRelative } from './libraries.ts';
import { compilerVersion } from './package-manager.ts';
import type { Definition } from './project.ts';
import { tyName } from './types.ts';
import type { HttpPolicyPlan } from './http-policies.ts';
import { action, attempt, branch, choice, coordinate, flow, loop, paragraph, renderSpecTree, scope, section, sequence, step, type FlowNode, type SpecNode } from './spec-tree.ts';
import { specHint } from './spec-hints.ts';

const generated = '<!-- Generated by aug spec. Edit the August source, then regenerate. -->';
const copied = '// Generated by aug spec. This is a copy of the installed dependency source.\n';
const code = (value: string) => {const text=value.replaceAll('\n','\\n');const fence='`'.repeat(1+Math.max(0,...(text.match(/`+/g)??[]).map(part=>part.length)));return fence+(text.startsWith('`')?' ':'')+text+(text.endsWith('`')?' ':'')+fence;};
const url = (value: string) => value.replaceAll('\\', '/').split('/').map(encodeURIComponent).join('/');
const anchor = (name: string) => 'symbol-' + name;
const hash = (text: string) => createHash('sha256').update(text).digest('hex');
const compare = (left:string, right:string) => left < right ? -1 : left > right ? 1 : 0;
const unreachable = (node: never): never => { throw new Error(`No specification renderer for ${(node as {kind?:string}).kind}`); };
const plain = (text:string) => text.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replaceAll('`','');

export interface SpecOutput { path: string; text: string; source: string; kind?: 'source-hint' }
export interface SpecOptions { files?: SourceFile[]; manifest?: boolean }

/** Plan prose, managed source pointers, and versioned dependency copies without writes or execution. */
export function generateSpecs(checked: CheckedProject, options: SpecOptions = {}): SpecOutput[] {
  if (checked.diagnostics.some(issue => issue.severity !== 'warning')) throw new Error('Fix compiler errors before generating specifications');
  const project = checked.project;
  const owned = options.files ?? [...project.files.values()].filter(file => !file.builtin && !file.package);
  const own = new Set(owned.map(file => file.path));
  const hints=owned.map(specHint), offsets=new Map(hints.map(hint=>[hint.file.path,hint.lineOffset]));
  const docs = new Map<string,string>(), sources = new Map<string,string>();
  for (const file of project.files.values()) {
    if (own.has(file.path)) { docs.set(file.path, file.path + '.md'); sources.set(file.path, file.path); continue; }
    const scope = file.package && project.packages.scopes.get(file.package);
    const identity = scope ? join('packages', scope.name, scope.version, relative(scope.sourceRoot, file.path)) :
      join('august', compilerVersion(), libraryRelative(project.libraries, file.path));
    const source = join(project.root, '.aug-spec', identity);
    docs.set(file.path, source + '.md'); sources.set(file.path, source);
  }
  const queue = [...owned].sort((a,b) => compare(a.path,b.path));
  const seen = new Set<string>(), outputs: SpecOutput[] = hints.map(hint=>({path:hint.file.path,text:hint.text,source:hint.file.path,kind:'source-hint'}));
  for (let index = 0; index < queue.length; index++) {
    const file = queue[index]; if (seen.has(file.path)) continue; seen.add(file.path);
    const writer = new SpecWriter(checked, file, docs, sources, own, offsets, path => {
      const dependency = project.files.get(path);
      if (dependency && !seen.has(path)) queue.push(dependency);
    });
    outputs.push({path:docs.get(file.path)!, text:writer.render(), source:file.path});
    if (!own.has(file.path)) outputs.push({path:sources.get(file.path)!, text:copied + file.source, source:file.path});
  }
  return outputs.sort((a,b) => compare(a.path,b.path));
}

class SpecWriter {
  private checked: CheckedProject;
  private file: SourceFile;
  private docs: Map<string,string>;
  private sources: Map<string,string>;
  private own: Set<string>;
  private offsets: Map<string,number>;
  private enqueue: (path:string) => void;
  private used = new Map<string,{def:Definition; operations:Set<MethodDecl>; fields:Set<string>; constructed?:boolean}>();
  private builtins = new Map<string,BuiltinOperation>();
  private properties = new Map<string,{type:string;documentation:string}>();
  private locals = new Map<string,TypeRef>();
  constructor(checked:CheckedProject, file:SourceFile, docs:Map<string,string>, sources:Map<string,string>, own:Set<string>, offsets:Map<string,number>, enqueue:(path:string)=>void) {
    this.checked=checked; this.file=file; this.docs=docs; this.sources=sources; this.own=own; this.offsets=offsets;this.enqueue=enqueue;
  }
  private definition(name:string): Definition|undefined { return this.checked.project.scopes.get(this.file.path)?.get(name); }
  private use(def:Definition|undefined, method?:MethodDecl, field?:string): void {
    if (!def || def.file === this.file.path) return;
    if(method&&'methods' in def.node&&!def.node.methods.includes(method)) {
      const owner=[...this.checked.project.definitions.values()].find(owner=>'methods' in owner.node&&owner.node.methods.includes(method!));
      this.use(owner,method); method=undefined;
    }
    let entry=this.used.get(def.id);
    if(!entry) {entry={def,operations:new Set(),fields:new Set()};this.used.set(def.id,entry);}
    if(method)entry.operations.add(method); if(field)entry.fields.add(field);
    this.enqueue(def.file);
  }
  private link(def:Definition, name=def.name, label=name): string {
    this.use(def);
    return `[${code(label)}](${url(relative(dirname(this.docs.get(this.file.path)!),this.docs.get(def.file)!))}#${encodeURIComponent(anchor(name))})`;
  }
  private source(span:Span): string {
    return `[source](${url(relative(dirname(this.docs.get(this.file.path)!),this.sources.get(span.file)!))}#L${span.line + (this.own.has(span.file)?this.offsets.get(span.file)??0:1)})`;
  }
  private heading(name:string, span:Span, level:number, children:SpecNode[], role?:string): SpecNode {
    return section(code(name)+(role?' · '+role:''),level,children,anchor(name),this.source(span));
  }
  private type(type:TypeRef, file=this.file.path): string {
    const enclosing=this.checked.project.files.get(file)?.items.filter(item=>'typeParams' in item&&item.span.start<=type.span.start&&item.span.end>=type.span.end)??[];
    const parameter=enclosing.some(item=>'typeParams' in item&&(item.typeParams.includes(type.name)||'methods' in item&&item.methods.some(method=>
      method.span.start<=type.span.start&&method.span.end>=type.span.end&&method.typeParams.includes(type.name))));
    const def=parameter?undefined:this.checked.project.scopes.get(file)?.get(type.name);this.use(def);type.args.forEach(arg=>this.type(arg,file));
    return def?this.link(def,def.name,typeName(type)):code(typeName(type));
  }
  private notes(doc?:Javadoc): string {
    if(!doc)return '';
    const prose=doc.markdown.split(/(?:^|\n\n)\*\*(?:Returns|Parameters|Throws|Deprecated:|See also:)/)[0].trim();
    const extra=(doc.tags??[]).filter(tag=>tag.name==='deprecated'||tag.name==='see').map(tag=>
      tag.name==='deprecated'?`Deprecated: ${tag.value}`:`See also: ${tag.value}`);
    return [prose,...extra].filter(Boolean).join(' ');
  }
  private generics(node:GenericHeader, file=this.file.path): string {
    return node.typeParams.length ? 'The type parameters are ' + coordinate(node.typeParams.map(name=>code(name)+
      (node.typeVariance?.[name]?` (${node.typeVariance[name] === 'out' ? 'produces values' : 'accepts values'})`:'')+
      (node.typeConstraints?.[name]?.length?` which must satisfy ${coordinate(node.typeConstraints[name].map(type=>this.type(type,file)))}`:'')))+'.':'';
  }
  private inputs(params:Param[], fields=false, file=this.file.path, descriptions=new Map<string,string>()): string {
    if(!params.length)return '';
    if(fields&&params.length===1&&params[0].injected) {
      const param=params[0];this.locals.set(param.name,param.type);
      return 'The '+code(param.name)+' dependency is injected as '+this.type(param.type,file)+' and stored '+(param.mutable?'mutably':'read-only')+
        (param.name.startsWith('_')?' and privately':'')+(param.ownership==='own'?' with ownership transferred':param.ownership==='borrow'?' with permission to mutate it':'')+
        (descriptions.has(param.name)?' ('+descriptions.get(param.name)!.replace(/[.!?]$/,'')+')':'')+'.';
    }
    const describe=(group:Param[])=>{
      const param=group[0];
      group.forEach(param=>this.locals.set(param.name,param.type));
      const name=coordinate(group.map(param=>code(param.label??param.name))), type=this.type(param.type,file);
      const simple:Record<string,string>={int:group.length===1?'an integer':'integers',float:group.length===1?'a number':'numbers',string:group.length===1?'a string':'strings',bool:group.length===1?'a boolean':'booleans'};
      let sentence=param.injected?coordinate(group.map(param=>code(param.name)))+' ('+type+')':name+' as '+(simple[param.type.name]&&!param.type.optional?simple[param.type.name]:type);
      if(param.source)sentence+=` from the HTTP ${param.source.kind}${param.source.name?' '+code(param.source.name):''}`;
      if(param.ownership==='own')sentence+=' with ownership transferred';
      else if(param.ownership==='borrow')sentence+=' with permission to mutate it during the call';
      if(fields)sentence+=`, kept ${param.mutable?'mutable':'read-only'}${param.name.startsWith('_')?' and private':''}${param.label&&param.label!==param.name?' as '+code(param.name):''}`;
      const description=descriptions.get(param.name);
      if(description)sentence+=' ('+description.replace(/[.!?]$/,'').replace(/^The /,'the ')+')';
      return sentence;
    };
    const groups=(injected:boolean)=>this.parameterGroups(params.filter(param=>param.injected===injected),fields,descriptions).map(describe);
    const supplied=groups(false), injected=groups(true);
    const queries=params.filter(param=>!param.injected&&param.source?.kind==='query');
    const onlyQueries=queries.length&&queries.length===params.filter(param=>!param.injected).length;
    const aliases=queries.filter(param=>param.source?.name&&param.source.name!==param.name);
    const typedQueries=queries.filter(param=>param.type.name!=='string');
    const suppliedText=onlyQueries?'It reads '+coordinate(queries.map(param=>code(param.source?.name??param.label??param.name)))+' from the HTTP query.'+
      (aliases.length?' '+coordinate(aliases.map(param=>code(param.source!.name!)+' is called '+code(param.name)+' here'))+'.':'')+
      (typedQueries.length?' It parses '+coordinate(typedQueries.map(param=>code(param.name)+' as '+this.type(param.type,file)))+'.':''):
      supplied.length?'It takes '+coordinate(supplied)+'.':'';
    return [suppliedText,injected.length?'It gets '+coordinate(injected)+' from dependency injection.':'',
      params.some(param=>param.type.optional)?'Omitted optional inputs are null.':''].filter(Boolean).join(' ');
  }
  private parameterGroups(params:Param[], fields=false, descriptions=new Map<string,string>()): Param[][] {
    const groups:Param[][]=[];
    const key=(value:Param)=>JSON.stringify([typeName(value.type),value.source,value.ownership,fields&&value.mutable,fields&&value.name.startsWith('_')]);
    const alias=(value:Param)=>fields&&value.label&&value.label!==value.name;
    for(const param of params) {
      const previous=groups.at(-1)?.[0];
      if(previous&&key(previous)===key(param)&&!descriptions.has(param.name)&&!descriptions.has(previous.name)&&!alias(param)&&!alias(previous))groups.at(-1)!.push(param);
      else groups.push([param]);
    }
    return groups;
  }
  private contract(method:MethodDecl, documentation?:Javadoc): SpecNode[] {
    const effects=this.checked.effectContracts.get(method);
    const layers=this.checked.interceptorPlans.get(method)??[];
    const errors=[...new Set([...method.throws.map(type=>{this.type(type,method.span.file);return typeName(type);}),...layers.flatMap(layer=>layer.errors.map(tyName))])];
    const changes=effects?.changes??method.changes??[];
    const uses=[...(effects?.uses.values()??method.uses??[])];
    const result:SpecNode[]=[];
    const generics=this.generics(method), inputs=this.inputs(method.params,false,method.span.file,documentation?.parameters);
    if(generics)result.push(paragraph(generics));
    if(inputs)result.push(paragraph(inputs));
    const facts:string[]=[];
    const returnNote=documentation?.tags?.find(tag=>tag.name==='return'||tag.name==='returns')?.value??
      documentation?.markdown.match(/\*\*Returns\*\* ([^\n]+)/)?.[1];
    // Implementations explain their actual returns below. Contracts need the
    // result type; repeating it before every return adds noise to the narrative.
    this.type(method.returns,method.span.file);
    if(method.returns.name!=='void'&&(!method.body||returnNote||method.returnOwnership==='own'))facts.push(`It returns ${(method.returnOwnership==='own'?'ownership of ':'')+this.type(method.returns,method.span.file)}`+
      (returnNote?` — ${returnNote.replace(/[.!?]$/,'')}`:'')+'.');
    if(changes.length)facts.push('It may change '+coordinate(changes.map(code))+'.');
    const capabilities=uses.map(effect=>{
      const def='capability' in effect?effect.capability?.def:undefined;
      const target=def??this.definition(effect.source);
      const operation=target&&'methods' in target.node?target.node.methods.find(method=>method.name===effect.operation):undefined;
      this.use(target,operation);
      return target?this.link(target,operation?`${target.name}.${operation.name}`:target.name,`${effect.source}.${effect.operation}`):code(`${effect.source}.${effect.operation}`);
    });
    if(capabilities.length&&!method.body)facts.push('It can call '+coordinate(capabilities)+'.');
    if(errors.length&&!method.endpoint)facts.push('Failures can raise '+coordinate(errors.map(name=>{
      const note=documentation?.tags?.find(tag=>(tag.name==='throws'||tag.name==='exception')&&tag.value.startsWith(name+' '))?.value.slice(name.length).trim()??
        documentation?.markdown.split('**Throws**\n')[1]?.split('\n\n')[0]?.split('\n').find(line=>line.startsWith('- '+code(name)+': '))?.slice(('- '+code(name)+': ').length);
      const def=this.checked.project.scopes.get(method.span.file)?.get(name);
      return (def?this.link(def):code(name))+(note?` (${note.replace(/[.!?]$/,'').replace(/^When\b/,'when')})`:'');
    }))+'.');
    if(facts.length)result.push(paragraph(facts.join(' ')));
    if(method.endpoint) {
      const endpoint=method.endpoint;
      if(endpoint.streams)result.push(paragraph(`It streams ${this.type(method.returns)} items.`));
      else if(endpoint.status!==200)result.push(paragraph(`A plain response body uses HTTP status ${endpoint.status}.`));
      if(endpoint.errors.length)result.push(paragraph('The handler responds with '+coordinate(endpoint.errors.map(error=>`HTTP ${error.status} for ${this.type(error.type)}`))+'.'));
      const unmapped=errors.filter(name=>!endpoint.errors.some(error=>typeName(error.type)===name));
      if(unmapped.length)result.push(paragraph('It can also raise '+coordinate(unmapped.map(code))+'.'));
    }
    return result;
  }
  private layers(node:MethodDecl|ClassDecl): SpecNode[] {
    const layers=this.checked.interceptorPlans.get(node)??[];
    const policies=node.kind==='function'?this.checked.httpPolicies.get(node)??[]:[];
    if(!layers.length&&!policies.length)return [];
    const steps:string[]=[];
    policies.forEach(policy=>{steps.push(this.policy(policy)+
      (node.kind==='function'&&policy.dependencies.length?' Use '+policy.dependencies.map(index=>code(node.params[index].name)).join(', ')+'.':''));});
    layers.forEach(layer=>{this.use(layer.definition,layer.around);steps.push(`Call ${this.link(layer.definition,`${layer.definition.name}.around`)}.`+
      (layer.annotation.mappings.length?' Map '+layer.annotation.mappings.map(mapping=>code(mapping.source)+' to '+code(mapping.name)).join(', ')+'.':''));});
    return [paragraph('Layers run in the declared order. '+steps.join(' ')),
      ...(policies.length?[paragraph('HTTP policies run before decoding; custom interceptors run after it.')]:[])];
  }
  private policy(policy:HttpPolicyPlan): string {
    const options=policy.options;
    switch(policy.name) {
      case 'RequireLogin':return 'Authenticate the request. If no identity is returned, finish with status 401.';
      case 'RequirePermission':return `Authenticate the request and authorize permission ${code(String(options.permission))}. No identity returns 401; denied permission returns 403.`;
      case 'LogRequest':return 'Call the request logger after transport completion or disconnect, in reverse layer order. Record disconnect as status 499. This layer observes rejections from layers inside it.';
      case 'RateLimit':return `Allow ${options.requests} requests per ${options.seconds} seconds for each endpoint and trusted transport peer. Ignore forwarding headers. Excess requests return 429.`;
      case 'Timeout':return `Set a deadline of ${options.milliseconds} milliseconds for the handler, child tasks, and response transport. Before output, expiry returns 504; after output, it closes the stream. Native calls finish before cooperative cancellation; buffered request reception precedes this deadline.`;
      case 'Cors':return `Allow origins ${code(JSON.stringify(options.origins))}. ${options.credentials?'Allow':'Do not allow'} credentials. `+
        (options.headers?`Allow request headers ${code(JSON.stringify(options.headers))}. `:'')+'A supplied disallowed origin returns 403. Preflight checks the route method and requested headers.';
      case 'Compress':return 'Negotiate gzip. Respect existing Content-Encoding and bodyless statuses. Encode stream items as complete concatenated gzip members.';
    }
  }
  private receiver(expr:Expr, operation?:string): Definition|undefined {
    const checked=this.checked.expressionTypes.get(expr);
    if(checked?.def)return checked.def;
    if(checked?.kind==='param')return checked.bounds?.find(bound=>bound.def&&(!operation||this.method(bound.def,operation)))?.def;
    const ref=expr.kind==='name'?this.locals.get(expr.name):undefined;
    if(ref)return this.definition(ref.name);
    if(expr.kind==='resolve')return this.checked.bindings.find(binding=>binding.key===expr.name)?.exposedType.def;
    if(expr.kind==='call'&&expr.callee.kind==='name') {
      const def=this.definition(expr.callee.name);
      if(def?.node.kind==='class')return def;
      if(def?.node.kind==='function')return this.definition(def.node.returns.name);
    }
    return undefined;
  }
  private method(def:Definition, name:string, seen=new Set<string>()): MethodDecl|undefined {
    if(seen.has(def.id))return;seen.add(def.id);
    if(!('methods' in def.node))return;
    const direct=def.node.methods.find(method=>method.name===name);if(direct)return direct;
    const refs=def.node.kind==='class'?def.node.implements:def.node.kind==='interface'?def.node.extends:[];
    for(const ref of refs){const parent=this.checked.project.scopes.get(def.file)?.get(ref.name);const inherited=parent&&this.method(parent,name,seen);if(inherited)return inherited;}
  }
  private expression(expr:Expr, nested=false): string {
    switch(expr.kind) {
      case 'literal':return expr.value===null?'null':code(expr.numericText??JSON.stringify(expr.value));
      case 'name': {const def=!this.locals.has(expr.name)?this.definition(expr.name):undefined;this.use(def);return def?this.link(def):code(expr.name);}
      case 'member': {
        const def=this.receiver(expr.object,expr.name);this.use(def,undefined,expr.name);
        const name=expr.name,receiverType=this.checked.expressionTypes.get(expr.object)?.name;
        const property=receiverType&&builtinProperties[receiverType]?.find(property=>property.name===name);
        if(property)this.properties.set(receiverType+'.'+name,{...property,type:this.checked.expressionTypes.get(expr)?tyName(this.checked.expressionTypes.get(expr)!):property.type});
        const object=this.expression(expr.object), path=this.memberPath(expr);
        return path?code(path):`${code(name)} of ${object}`;
      }
      case 'unary': {
        if(expr.op==='!'&&expr.value.kind==='binary'&&(expr.value.op==='=='||expr.value.op==='!='))
          return `${this.expression(expr.value.left,true)} ${expr.value.op==='=='?'does not equal':'equals'} ${this.expression(expr.value.right,true)}`;
        if(expr.op==='!'&&expr.value.kind==='call')return this.predicate(expr.value,false);
        return `${expr.op==='!'?'not':'the negative of'} (${this.expression(expr.value)})`;
      }
      case 'binary': {
        const words:Record<string,string>={'+':'plus','-':'minus','*':'times','/':'divided by','==':'equals','!=':'does not equal','<':'is less than','>':'is greater than','<=':'is at most','>=':'is at least','&&':'and','||':'or'};
        if(!words[expr.op])throw new Error(`No specification renderer for operator ${expr.op}`);
        if(expr.right.kind==='literal'&&expr.right.value===null&&['==','!='].includes(expr.op))
          return this.expression(expr.left)+(expr.op==='=='?' is null':' is not null');
        if(expr.right.kind==='literal'&&expr.right.value===0&&['>','<'].includes(expr.op))
          return this.expression(expr.left)+(expr.op==='>'?' is positive':' is negative');
        const textParts=this.stringParts(expr);
        if(expr.op==='+'&&textParts.length>=2) {
          const text=textParts.map(part=>part.kind==='literal'&&typeof part.value==='string'?
            part.value.replaceAll('{','{{').replaceAll('}','}}'):'{'+plain(this.expression(part))+'}').join('');
          return 'the text '+code(text);
        }
        const child=(value:Expr)=>this.expression(value,value.kind==='binary'&&!(['&&','||'].includes(expr.op)&&
          (value.op===expr.op||['==','!=','<','>','<=','>='].includes(value.op))));
        const result=`${child(expr.left)} ${words[expr.op]} ${child(expr.right)}`;
        return nested?`(${result})`:result;
      }
      case 'collection': {
        if(expr.collection==='Map')return 'a map with '+expr.items.filter((_,index)=>index%2===0).map((key,index)=>`${this.expression(key)} mapped to ${this.expression(expr.items[index*2+1])}`).join('; ');
        return `a ${expr.collection==='empty'?'context-typed empty collection':expr.collection.toLowerCase()}`+(expr.items.length?' containing '+expr.items.map(item=>this.expression(item)).join(', '):' with no items');
      }
      case 'resolve':return `the instance provided for ${code(expr.name)}${expr.typeArgs.length?' with type arguments '+expr.typeArgs.map(type=>this.type(type)).join(', '):''}`;
      case 'call': {
        const action=this.call(expr);
        const known=this.knownValue(expr);if(known)return known;
        if(expr.callee.kind==='member') {
          const receiver=expr.callee.object, type=this.checked.expressionTypes.get(receiver)?.name;
          if(!this.receiver(receiver)&&['string','Bytes','List','Set','Map','Tuple'].includes(type??'')&&!expr.args.length) {
            const value=this.expression(receiver);
            if(expr.callee.name==='bytes'&&type==='string')return 'the UTF-8 bytes of '+value;
            if(expr.callee.name==='base64url'&&type==='Bytes')return 'the URL-safe base64 encoding of '+value;
            if(expr.callee.name==='length')return (type==='string'||type==='Bytes'?'the byte length of ':'the number of elements in ')+value;
          }
        }
        const name=expr.callee.kind==='name'?expr.callee.name:'';
        return action.startsWith('construct ')?(/^[AEIOU]/i.test(name)?'an ':'a ')+action.slice('construct '.length):
          action.startsWith('call ')?action.slice('call '.length):action;
      }
      case 'start':return `a child task running ${this.expression(expr.call)} with its inputs captured now`;
      case 'wait':return `the result of waiting for ${expr.tasks.map(task=>this.expression(task)).join(' and ')}${expr.tasks.length>1?' in input order':''}; propagate failures`;
      case 'handle': {const plan=this.checked.actions.get(expr), endpoint=plan?.endpoint.node.kind==='function'?plan.endpoint.node.endpoint:undefined;
        const captures=expr.call.kind==='call'?expr.call.args.filter(value=>value.kind!=='formInput').map(value=>this.expression(value)):[];
        return endpoint?`a form action that sends ${code(endpoint.method+' '+endpoint.path)} to ${this.link(plan!.endpoint)} on submission`+
          (captures.length?' with captured '+coordinate(captures):''):`a form action for ${this.expression(expr.call)}`;}
      case 'formInput':return 'the submitted form data';
      case 'markupText':return code(expr.text);
      case 'markup': {
        const def=this.definition(expr.tag);this.use(def);
        const elements:Record<string,string>={p:'a paragraph',h1:'a heading',h2:'a heading',button:'a button',a:'a link'};
        return (def?'the server component '+this.link(def):elements[expr.tag]??'the HTML element '+code(expr.tag||'fragment'))+
          (expr.attributes.length?' with '+expr.attributes.map(attribute=>`${code(attribute.name)} = ${this.expression(attribute.value)}`).join(', '):'')+
          (expr.children.length?' containing '+expr.children.map(child=>this.expression(child)).join(', '):'')+
          ' with escaped text';
      }
      default:return unreachable(expr);
    }
  }
  private memberPath(expr:Expr): string|undefined {
    if(expr.kind==='name'&&!this.definition(expr.name))return expr.name;
    if(expr.kind==='name'&&this.locals.has(expr.name))return expr.name;
    if(expr.kind==='member') {const object=this.memberPath(expr.object);return object?object+'.'+expr.name:undefined;}
  }
  private argument(expr:Extract<Expr,{kind:'call'}>, label:string): Expr|undefined {
    const explicit=expr.args.findIndex((arg,index)=>(expr.argLabels[index]??(arg.kind==='name'?arg.name:''))===label);
    if(explicit>=0)return expr.args[explicit];
    const plan=this.checked.callPlans.get(expr);
    const def=expr.callee.kind==='name'?this.definition(expr.callee.name):expr.callee.kind==='member'?this.receiver(expr.callee.object,expr.callee.name):undefined;
    const method=def?.node.kind==='function'?def.node:expr.callee.kind==='member'&&def?this.method(def,expr.callee.name):undefined;
    const params=method?.params??(def?.node.kind==='class'?def.node.fields:[]);
    const slot=params.findIndex(param=>(param.label??param.name)===label);
    const index=slot>=0?plan?.sourceIndices[slot]:undefined;
    return index!==undefined&&index>=0?expr.args[index]:undefined;
  }
  /** Interpret only compiler built-ins and the canonical standard-library contracts. */
  private standardOperation(expr:Extract<Expr,{kind:'call'}>): string|undefined {
    if(expr.callee.kind!=='member')return;
    const def=this.receiver(expr.callee.object,expr.callee.name);
    if(!def||!this.checked.project.files.get(def.file)?.builtin)return;
    return libraryRelative(this.checked.project.libraries,def.file).replaceAll('\\','/')+':'+def.name+'.'+expr.callee.name;
  }
  private knownValue(expr:Extract<Expr,{kind:'call'}>): string|undefined {
    const arg=(label:string)=>{const value=this.argument(expr,label);return value?this.expression(value):undefined;};
    const receiver=expr.callee.kind==='member'?this.expression(expr.callee.object):'';
    switch(this.standardOperation(expr)) {
      case 'crypto/contracts.aug:Crypto.random':case 'crypto/contracts.aug:GnuTlsCrypto.random':
        return `${arg('size')} random bytes from ${receiver}`;
      case 'crypto/contracts.aug:Crypto.decodeBase64url':case 'crypto/contracts.aug:GnuTlsCrypto.decodeBase64url':
        return `${arg('input')} decoded as URL-safe base64 by ${receiver}`;
      case 'time/contracts.aug:Clock.now':case 'time/contracts.aug:SystemClock.now':return 'the current time from '+receiver;
      case 'memory/store.aug:ExpiringStore.take':case 'memory/store.aug:MemoryStore.take':
        return `the live value removed from ${receiver} under ${arg('key')}, using ${arg('now')} as the current time`;
      case 'memory/store.aug:ExpiringStore.get':case 'memory/store.aug:MemoryStore.get':
        return `the live value in ${receiver} under ${arg('key')}, using ${arg('now')} as the current time`;
    }
    if(expr.callee.kind==='member'&&!this.receiver(expr.callee.object)) {
      const type=this.checked.expressionTypes.get(expr.callee.object)?.name;
      if(expr.callee.name==='get'&&type==='List')return `the item at index ${arg('index')} in ${receiver}`;
      if(expr.callee.name==='get'&&type==='Map')return `the value under ${arg('key')} in ${receiver}`;
      if(expr.callee.name==='contains'&&type==='Map')return `whether ${receiver} contains the key ${arg('key')}`;
      if(expr.callee.name==='contains'&&type==='Set')return `whether ${receiver} contains ${arg('value')}`;
      if(expr.callee.name==='with'&&type==='Headers')return `${receiver} with the header ${arg('name')} set to ${arg('value')}`;
    }
    if(expr.callee.kind==='name') {
      const def=this.definition(expr.callee.name);
      if(def?.file&&this.checked.project.files.get(def.file)?.builtin&&libraryRelative(this.checked.project.libraries,def.file).replaceAll('\\','/')==='web/contracts.aug'&&def.name==='urlEncode')
        return 'URL-encoded '+arg('input');
      if(this.checked.expressionTypes.get(expr)?.name==='Html') {
        const message=this.argument(expr,'message');
        if(message&&expr.args.length===1)return this.expression(expr.callee)+' showing '+this.expression(message);
      }
    }
    if(expr.callee.kind==='name'&&!this.definition(expr.callee.name)&&expr.callee.name==='HttpResponse') {
      const body=arg('body'), status=arg('status')??'200', headers=arg('headers');
      return `HTTP ${status.replaceAll('`','')} with ${body??'an empty body'}`+(headers?' and '+headers+' headers':'');
    }
  }
  private predicate(expr:Extract<Expr,{kind:'call'}>, expected=true): string {
    this.call(expr);
    if(expr.callee.kind==='member'&&!this.receiver(expr.callee.object)&&
      this.checked.expressionTypes.get(expr.callee.object)?.name==='string'&&expr.callee.name==='isToken') {
      const min=this.argument(expr,'min'),max=this.argument(expr,'max');
      return this.expression(expr.callee.object)+` is ${expected?'':'not '}a URL-safe ASCII token`+
        (min&&max?' with '+this.expression(min)+' to '+this.expression(max)+' characters':'');
    }
    const operation=this.standardOperation(expr);
    if(operation==='crypto/contracts.aug:Crypto.equal'||operation==='crypto/contracts.aug:GnuTlsCrypto.equal') {
      const left=this.argument(expr,'left')!,right=this.argument(expr,'right')!;
      return this.expression(left)+' and '+this.expression(right)+(expected?' match':' differ')+' when compared by '+this.expression(expr.callee.kind==='member'?expr.callee.object:expr.callee);
    }
    return this.expression(expr)+` returns ${expected?'true':'false'}`;
  }
  private call(expr:Extract<Expr,{kind:'call'}>): string {
    if(expr.callee.kind==='name'&&['List','Set','Map'].includes(expr.callee.name)&&!this.definition(expr.callee.name)) {
      const name=expr.callee.name, types=expr.typeArgs.map(type=>this.type(type));
      const items=expr.args.map(arg=>this.expression(arg));
      const label=name==='Map'?'map from '+(types[0]??'any')+' to '+(types[1]??'any'):
        name.toLowerCase()+' of '+(types[0]??'any');
      return items.length?'a '+label+' containing '+items.join(', '):'an empty '+label;
    }
    let target:string, method:MethodDecl|undefined, constructs=false;
    if(expr.callee.kind==='name') {
      const name=expr.callee.name;
      const def=this.definition(expr.callee.name);this.use(def);
      if(def?.node.kind==='class'&&def.file!==this.file.path)this.used.get(def.id)!.constructed=true;
      constructs=def?.node.kind==='class'||!def&&Object.hasOwn(builtinTypes,name);
      method=def?.node.kind==='function'?def.node:undefined;
      const builtin=!def&&builtinFunctions.find(operation=>operation.name===name);
      if(builtin)this.builtins.set(builtin.name,builtin);
      target=def?this.link(def):code(expr.callee.name);
    }else if(expr.callee.kind==='member') {
      const name=expr.callee.name;
      const def=this.receiver(expr.callee.object,expr.callee.name);method=def&&this.method(def,expr.callee.name);this.use(def,method);
      const receiver=this.checked.expressionTypes.get(expr.callee.object);
      const receiverType=receiver?.name??(expr.callee.object.kind==='name'?this.locals.get(expr.callee.object.name)?.name:undefined);
      const builtin=!def&&receiverType&&collectionOperations[receiverType]?.find(operation=>operation.name===name);
      if(builtin)this.builtins.set((receiver?tyName(receiver):receiverType)+'.'+builtin.name,{
        ...builtin,
        parameters:builtin.parameters.map(param=>({...param,type:receiver?tyName(operationType(param.type,receiver)):param.type})),
        returns:this.checked.expressionTypes.get(expr)?tyName(this.checked.expressionTypes.get(expr)!):builtin.returns,
      });
      // An inherited operation links to the interface that actually declares it.
      const owner=method&&[...this.checked.project.definitions.values()].find(def=>'methods' in def.node&&def.node.methods.includes(method!));
      this.use(owner,method);
      const object=this.expression(expr.callee.object),path=this.memberPath(expr.callee);
      target=owner?this.link(owner,`${owner.name}.${method!.name}`,path??expr.callee.name):code(path??expr.callee.name);
      if(!path)target+=' on '+object;
    }else target=this.expression(expr.callee);
    expr.typeArgs.forEach(type=>this.type(type));
    const plan=this.checked.callPlans.get(expr);
    const parameters=method?.params??(expr.callee.kind==='name'&&this.definition(expr.callee.name)?.node.kind==='class'?
      (this.definition(expr.callee.name)!.node as ClassDecl).fields:[]);
    const inputs=expr.args.map((arg,index)=>{
      const slot=plan?.sourceIndices.indexOf(index);
      const label=expr.argLabels[index]??(slot!==undefined&&slot>=0?parameters[slot]?.label??parameters[slot]?.name:arg.kind==='name'?arg.name:undefined);
      const same=arg.kind==='name'&&arg.name===label||arg.kind==='member'&&arg.name===label;
      const value=this.expression(arg);
      return label&&!same?code(label)+(arg.kind==='literal'?' ':' from ')+value:value;
    });
    let text=`${constructs?'construct':'call'} ${target}`+(expr.typeArgs.length?' for '+coordinate(expr.typeArgs.map(type=>this.type(type))):'')+(inputs.length?' with '+coordinate(inputs):'');
    const injected=parameters.flatMap((param,index)=>{
      if(!param.injected)return [];
      const source=plan?.injectionSources?.[index]??plan?.bindingKeys[index]??typeName(param.type);
      return [code(source)+(source===param.name?'':' for '+code(param.name))];
    });
    if(injected.length)text+=' using injected '+coordinate(injected);
    return text;
  }
  private stringParts(expr:Expr): Expr[] {
    if(expr.kind==='binary'&&expr.op==='+'&&this.checked.expressionTypes.get(expr)?.name==='string')
      return [...this.stringParts(expr.left),...this.stringParts(expr.right)];
    return [expr];
  }
  private joinedText(target:string, value:Expr): FlowNode|undefined {
    if(this.stringParts(value).length<2)return;
    return step(`It builds ${target} as ${this.expression(value)}.`);
  }
  private headerFields(value:Expr): {base:Expr; fields:string[]}|undefined {
    let current=value;
    const calls:Extract<Expr,{kind:'call'}>[]=[];
    while(current.kind==='call'&&current.callee.kind==='member'&&current.callee.name==='with'&&
      this.checked.expressionTypes.get(current.callee.object)?.name==='Headers') {
      const labels=current.args.map((arg,index)=>current.kind==='call'?
        current.argLabels[index]??(arg.kind==='name'?arg.name:''):''),
        name=labels.indexOf('name'),value=labels.indexOf('value');
      if(name<0||value<0)return;
      calls.unshift(current);
      current=current.callee.object;
    }
    if(calls.length<3)return;
    const operation=collectionOperations.Headers?.find(operation=>operation.name==='with');
    if(operation)this.builtins.set('Headers.with',operation);
    return {base:current,fields:calls.map(call=>{
      const labels=call.args.map((arg,index)=>call.argLabels[index]??(arg.kind==='name'?arg.name:''));
      return `${this.expression(call.args[labels.indexOf('name')])} to ${this.expression(call.args[labels.indexOf('value')])}`;
    })};
  }
  private statements(body:Stmt[]): FlowNode[] {
    const result:FlowNode[]=[];
    for(let index=0;index<body.length;index++) {
      const stmt=body[index], nodes=this.statement(stmt), tail=body[index+1];
      // A terminal guard and final return are exact alternatives, even without a written else.
      if(stmt.kind==='if'&&!stmt.otherwise.length&&index===body.length-2&&tail?.kind==='return'&&
        stmt.then.at(-1)?.kind==='return'&&nodes[0].kind==='branch') {
        nodes[0].otherwise=this.statement(tail);index++;
      }
      result.push(...nodes);
    }
    return result;
  }
  private statement(stmt:Stmt): FlowNode[] {
    const nodes=this.explainStatement(stmt);
    // Source identities survive sentence aggregation. Two identical calls are still two facts.
    nodes[0].source=`${stmt.span.file}:${stmt.span.start}:${stmt.span.end}`;
    return nodes;
  }
  private explainStatement(stmt:Stmt): FlowNode[] {
    const nested=(body:Stmt[])=>this.statements(body);
    switch(stmt.kind) {
      case 'assign': {
        if(stmt.target.kind==='name') {
          const type=stmt.declaredType??this.checked.expressionTypes.get(stmt.value);
          if(type)this.locals.set(stmt.target.name,{name:type.name,args:[],nullable:type.nullable,optional:type.optional,span:stmt.span});
          else if(stmt.value.kind==='call'&&stmt.value.callee.kind==='name') {const def=this.definition(stmt.value.callee.name);if(def?.node.kind==='class')this.locals.set(stmt.target.name,{name:def.name,args:[],nullable:false,span:stmt.span});}
        }
        if(stmt.declaredType)this.type(stmt.declaredType);
        const target=this.expression(stmt.target)+(stmt.declaredType&&!['int','float','string','bool'].includes(stmt.declaredType.name)?' of type '+this.type(stmt.declaredType):'');
        const headers=this.headerFields(stmt.value);
        const arithmetic=stmt.value.kind==='binary'&&['+','-'].includes(stmt.value.op)&&stmt.value.left.kind==='name'&&stmt.target.kind==='name'&&stmt.target.name===stmt.value.left.name&&['int','float','c_int'].includes(this.checked.expressionTypes.get(stmt.value)?.name??'');
        const headerLead=headers?`set ${target} from ${this.expression(headers.base)} by adding these header fields in order`:undefined;
        const getter=stmt.value.kind==='call'&&!stmt.value.args.length&&stmt.value.callee.kind==='name'&&this.definition(stmt.value.callee.name)?.node.kind==='function';
        const explanation=headers?sequence('It '+headerLead!.replace(/^set /,'sets '),headers.fields,headerLead):
          getter?step('It gets '+target+' from '+this.expression(stmt.value)+'.'):
          this.joinedText(target,stmt.value)??(arithmetic&&stmt.value.kind==='binary'?action(stmt.value.op==='+'?'increase':'decrease',`${target} by ${this.expression(stmt.value.right)}`):action('set',`${target} to ${this.expression(stmt.value)}`));
        return stmt.ownership==='own'?[explanation,step(`${target} owns this value.`)]:[explanation];
      }
      case 'destructure':return [action('split',`${this.expression(stmt.value)} into ${coordinate(stmt.names.map(code))} in order`)];
      case 'expr': {
        if(stmt.expr.kind==='literal'&&stmt.expr.value===null)return [action('continue','without an operation')];
        if(stmt.expr.kind==='call') {
          const call=this.call(stmt.expr);
          if(stmt.expr.callee.kind==='name'&&!this.definition(stmt.expr.callee.name)) {
            if(stmt.expr.callee.name==='print')return [step('It prints '+this.expression(stmt.expr.args[0])+'.')];
            if(stmt.expr.callee.name==='assert')return [step('The test requires '+this.condition(stmt.expr.args[0])+'.')];
          }
          if(stmt.expr.callee.kind==='member') {
            const receiver=stmt.expr.callee.object, def=this.receiver(receiver,stmt.expr.callee.name), method=def&&this.method(def,stmt.expr.callee.name);
            const type=this.checked.expressionTypes.get(receiver)?.name;
            const arg=(name:string)=>this.expression(this.argument(stmt.expr as Extract<Expr,{kind:'call'}>,name)!);
            if(!def) {
              if(type==='List'&&stmt.expr.callee.name==='append')return [step('It appends '+arg('value')+' to '+this.expression(receiver)+'.')];
              if(type==='Set'&&stmt.expr.callee.name==='add')return [step('It adds '+arg('value')+' to '+this.expression(receiver)+'.')];
              if(type==='Map'&&stmt.expr.callee.name==='set')return [step('It stores '+arg('value')+' in '+this.expression(receiver)+' under '+arg('key')+'.')];
              if(type==='Map'&&stmt.expr.callee.name==='take')return [step('It removes the key '+arg('key')+' from '+this.expression(receiver)+'.')];
            }
            if(method?.returns.name==='void'&&method.params.filter(param=>!param.injected).length===1&&stmt.expr.args.length===1) {
              const owner=[...this.checked.project.definitions.values()].find(owner=>'methods' in owner.node&&owner.node.methods.includes(method))!;
              const target=this.link(owner,owner.name+'.'+method.name,this.memberPath(stmt.expr.callee)??method.name);
              const plan=this.checked.callPlans.get(stmt.expr);
              const injected=method.params.flatMap((param,index)=>param.injected?[code(plan?.injectionSources?.[index]??plan?.bindingKeys[index]??typeName(param.type))]:[]);
              return [step('It passes '+this.expression(stmt.expr.args[0])+' to '+target+(injected.length?', using injected '+coordinate(injected):'')+'.')];
            }
          }
          const stored=this.standardOperation(stmt.expr);
          if(stored==='memory/store.aug:ExpiringStore.put'||stored==='memory/store.aug:MemoryStore.put') {
            const arg=(name:string)=>this.expression(this.argument(stmt.expr as Extract<Expr,{kind:'call'}>,name)!);
            return [step(`It stores ${arg('value')} in ${this.expression(stmt.expr.callee.kind==='member'?stmt.expr.callee.object:stmt.expr.callee)} under ${arg('key')}, expiring at ${arg('expires')}. The current time for this write is ${arg('now')}.`)];
          }
          if(call.startsWith('call '))return [action('call',call.slice(5))];
          if(call.startsWith('construct '))return [action('construct',call.slice(10))];
        }
        return [action('evaluate',this.expression(stmt.expr))];
      }
      case 'return': {
        if(!stmt.value)return [action('return','without a value')];
        const headers=this.headerFields(stmt.value);
        if(headers) {
          const lead=`return headers starting with ${this.expression(headers.base)} and adding these fields in order`;
          return [sequence('It '+lead.replace(/^return /,'returns '),headers.fields,lead)];
        }
        return [action('return',this.expression(stmt.value))];
      }
      case 'throw':return [action('fail','with '+this.expression(stmt.value))];
      case 'yield':return [action('send',this.expression(stmt.value)+' as the next stream item')];
      case 'if': {
        const node=branch(this.condition(stmt.test),nested(stmt.then),nested(stmt.otherwise));
        if(node.kind==='branch'&&!stmt.otherwise.length&&stmt.then.length===1&&stmt.then[0].kind==='throw'&&
          stmt.then[0].value.kind==='call'&&stmt.then[0].value.args.length===0)node.requirement=this.requirement(stmt.test);
        return [node];
      }
      case 'while':return [loop('While '+this.condition(stmt.test),nested(stmt.body),'Repeat this loop while its condition remains true.')];
      case 'for':return [loop('For each '+coordinate(stmt.names.map(code))+' in a snapshot of '+this.expression(stmt.iterable),nested(stmt.body),'Repeat these steps for each remaining item in the snapshot.')];
      case 'match': {
        const value=this.expression(stmt.value);
        const terminal=(body:Stmt[])=>['return','throw'].includes(body.at(-1)?.kind??'');
        // A null guard that exits is followed only by the non-null path. This is
        // a sequential explanation, not a nested tour through match syntax.
        if(stmt.cases.length===2&&stmt.cases[0].pattern==='null'&&terminal(stmt.cases[0].body)&&stmt.cases[1].pattern==='some') {
          const read=stmt.value.kind==='call', second=stmt.cases[1];
          const first=branch(read?'no value is found':value+' is null',nested(stmt.cases[0].body));
          return [...(read?[step('It obtains '+value+'.')]:[]),first,
            step('The non-null '+(read?'result':value)+' becomes '+code(second.name!)+'.'),...nested(second.body)];
        }
        return [choice(value,stmt.cases.map(clause=>{
          const condition=clause.pattern==='else'?'Otherwise':clause.pattern==='some'?'If '+value+' is not null, using '+code(clause.name!)+' for it':
            clause.pattern==='type'?'If '+value+' satisfies '+this.type(clause.type!)+', using '+code(clause.name!)+' for it':
            clause.pattern==='literal'?'If '+value+' equals '+this.expression(clause.literal!):'If '+value+' is null';
          return {condition,children:nested(clause.body)};
        }))];
      }
      case 'try':return [attempt(nested(stmt.body),stmt.catches.map(clause=>({error:this.type(clause.type),name:code(clause.name),children:nested(clause.body)})),stmt.always?nested(stmt.always):undefined)];
      case 'unsafe':return [scope('Within an unsafe block',nested(stmt.body),'Native operations must satisfy their declared C contracts.')];
      case 'borrow':return [scope('With temporary permission to change '+code(stmt.name),nested(stmt.body),'')];
      case 'scope':return [scope('Within a task and ownership scope',nested(stmt.body),'On leaving this scope, join its child tasks and release its local values.')];
      case 'lock':return [scope('While holding the lock on '+this.expression(stmt.value)+' as mutable '+code(stmt.name),nested(stmt.body),'Release this lock when the block exits, including on return or failure.')];
      case 'freeze':return [action('freeze',this.expression(stmt.value)+' as '+code(stmt.name)),step('The immutable value is shared without copying it.')];
      case 'serve':return [action('serve',coordinate(stmt.names.map(name=>{const def=this.definition(name);return def?this.link(def):code(name);}))+' on port '+this.expression(stmt.port))];
      default:return unreachable(stmt);
    }
  }
  private condition(expr:Expr): string {
    return expr.kind==='call'?this.predicate(expr):this.expression(expr)+(['binary','unary'].includes(expr.kind)?'':' is true');
  }
  private requirement(expr:Expr, nested=false): string {
    if(expr.kind==='unary'&&expr.op==='!')return this.condition(expr.value);
    if(expr.kind==='binary') {
      if(expr.op==='||'||expr.op==='&&') {
        if(expr.op==='&&'&&expr.left.kind==='binary'&&expr.right.kind==='binary'&&expr.left.op==='!='&&expr.right.op==='!='&&
          this.memberPath(expr.left.left)===this.memberPath(expr.right.left)&&this.memberPath(expr.left.left))
          return this.expression(expr.left.left)+' is either '+this.expression(expr.left.right)+' or '+this.expression(expr.right.right);
        const child=(value:Expr)=>this.requirement(value,value.kind==='binary'&&['&&','||'].includes(value.op)&&value.op!==expr.op);
        const text=child(expr.left)+(expr.op==='||'?' and ':' or ')+child(expr.right);
        return nested?'('+text+')':text;
      }
      const inverse:Record<string,string>={'==':'does not equal','!=':'equals','<':'is at least','>':'is at most','<=':'is greater than','>=':'is less than'};
      if(inverse[expr.op])return this.expression(expr.left,true)+' '+inverse[expr.op]+' '+this.expression(expr.right,true);
    }
    return expr.kind==='call'?this.predicate(expr,false):this.expression(expr)+' is false';
  }
  private binding(binding:BindDecl): string {
    const info=this.checked.bindings.find(info=>info.declaration===binding);
    const def=this.definition(binding.target.name);this.use(def);
    const lifetime=binding.lifetime??info?.lifetime;
    const key=binding.key+(binding.keyTypeArgs.length?'<'+binding.keyTypeArgs.map(type=>typeName(type)).join(', ')+'>':'');
    return (`${code(key)} is provided by ${def?this.link(def,def.name,typeName(binding.target)):this.type(binding.target)}. `+
      (lifetime==='shared'?'The same instance is shared. ':lifetime==='scoped'?'Each scope shares one instance. ':lifetime==='fresh'?'Each resolve creates a new instance. ':'Stateless instances are reused; stateful instances are created for each resolve. ')+
      (binding.sharedMutation?'Shared mutation is allowed. ':'')+
      (info?.dependencies.length?'It requires bindings for '+coordinate(info.dependencies.map(code))+'. ':'')).trimEnd();
  }
  private callable(method:MethodDecl, owner?:Definition): SpecNode {
    this.locals=new Map(owner&&'fields' in owner.node?fieldsOf(owner.node as ClassDecl).map(field=>[field.name,field.type]):[]);
    const name=owner&&owner.node.kind!=='function'?`${owner.name}.${method.name}`:method.name;
    const documentation=callableDocumentation(this.checked.project,method,owner);
    const children:SpecNode[]=[];
    if(method.endpoint)children.push(paragraph(code(method.name)+' handles '+code(method.endpoint.method+' '+method.endpoint.path)+'.'));
    if(method.name.startsWith('_'))children.push(paragraph('It is private to its defining scope.'));
    const notes=this.notes(documentation);
    if(notes)children.push(paragraph(notes));
    children.push(...this.contract(method,documentation),...this.layers(method));
    if(method.body)children.push(flow(this.statements(method.body)));
    else if(method.externC)children.push(paragraph('Native C implementation; only its declared contract is visible here.'));
    return this.heading(name,method.span,owner&&owner.node.kind!=='function'?3:2,children);
  }
  private exportLine(item:Extract<TopLevel,{kind:'export'}>): string {
    const folder=this.file.builtin?libraryChild(this.checked.project.libraries,dirname(this.file.path),item.name):join(dirname(this.file.path),item.name);
    const file=item.folder?join(folder,'export.aug'):join(dirname(this.file.path),item.from+'.aug');
    this.enqueue(file);
    return `Export ${item.folder?'the folder ':'the declaration '}${code(item.name)} from [${code(basename(file))}](${url(relative(dirname(this.docs.get(this.file.path)!),this.docs.get(file)!))}${item.folder?'':'#'+encodeURIComponent(anchor(item.name))}).`;
  }
  private providerLine(item:BindDecl|Extract<TopLevel,{kind:'include'}>): string {
    if(item.kind==='bind')return this.binding(item);
    const def=this.definition(item.name);
    return 'Include providers from '+(def?this.link(def):code(item.name))+'.';
  }
  private declaration(item:TopLevel): SpecNode {
    switch(item.kind) {
      case 'function':return this.callable(item);
      case 'class': {
        const def=this.definition(item.name)!;this.locals=new Map();
        const documentation=javadocBefore(this.file.source,item.annotations?.[0]?.span.start??item.span.start);
        const children:SpecNode[]=[];
        const generics=this.generics(item), notes=this.notes(documentation);
        const inputs=this.inputs(item.fields,true,this.file.path,documentation?.parameters);
        const implementsText=item.implements.length?'It implements '+coordinate(item.implements.map(type=>this.type(type)))+'.':'';
        const introduction=[notes,implementsText,item.name.startsWith('_')?'It is private to this file.':'',generics].filter(Boolean).join(' ');
        if(introduction)children.push(paragraph(introduction));
        if(inputs)children.push(paragraph(inputs));
        children.push(...this.layers(item));
        if(item.validationErrors?.length)children.push(paragraph('Construction can fail with '+item.validationErrors.map(type=>this.type(type)).join(', ')+'.'));
        if(item.stateFields?.length)children.push(...item.stateFields.map(field=>{this.locals.set(field.name,field.type);return paragraph(`The ${field.mutable?'mutable':'read-only'}${field.name.startsWith('_')?', private':''} field ${code(field.name)} has type ${this.type(field.type)} and starts as ${this.expression(field.initializer)}.`);}));
        if(item.constructorBody)children.push(this.heading(item.name+'.initialize',item.span,3,[flow(this.statements(item.constructorBody))]));
        if(!item.record) {
          const defaults=this.checked.defaults.get(def.id);
          const inherited=[...(defaults?.values()??[])].filter(info=>!item.methods.some(method=>method.name===info.method.name));
          if(inherited.length)children.push(paragraph('It inherits the default implementations of '+coordinate(inherited.map(info=>{const parent=this.checked.project.definitions.get(info.from);this.use(parent,info.method);return parent?this.link(parent,`${parent.name}.${info.method.name}`):code(info.method.name);}))+'.'));
        }
        children.push(...item.methods.map(method=>this.callable(method,def)));
        return this.heading(item.name,item.span,2,children,item.record?'immutable record':'class');
      }
      case 'interface':case 'interceptor': {
        const def=this.definition(item.name)!;this.locals=new Map();
        const generics=this.generics(item),notes=this.notes(javadocBefore(this.file.source,item.span.start));
        const role=item.kind==='interceptor'?'interceptor':item.capability?'capability interface':'interface';
        const introduction=[notes,item.name.startsWith('_')?'It is private to this file.':'',generics].filter(Boolean).join(' ');
        const children:SpecNode[]=introduction?[paragraph(introduction)]:[];
        if(item.kind==='interface'&&item.extends.length)children.push(paragraph('It inherits '+coordinate(item.extends.map(type=>this.type(type)))+'.'));
        if(item.kind==='interceptor') {
          const inputs=this.inputs(item.fields,true);
          if(inputs)children.push(paragraph(inputs));
          children.push(paragraph('Creates one interceptor per invocation. Its around operation may delegate once or finish early.'));
        }
        children.push(...item.methods.map(method=>this.callable(method,def)));
        return this.heading(item.name,item.span,2,children,role);
      }
      case 'composition': {
        const notes=this.notes(javadocBefore(this.file.source,item.span.start));
        return this.heading(item.name,item.span,2,[...(notes?[paragraph(notes)]:[]),paragraph('These providers are registered before startup. '+item.bindings.map(binding=>this.binding(binding)).join(' '))]);
      }
      case 'test':return this.tests(item);
      case 'bind':case 'include':return paragraph(this.providerLine(item));
      case 'export':return paragraph(this.exportLine(item));
      case 'import':return paragraph('');
      default:return flow(this.statement(item));
    }
  }
  private tests(suite:TestDecl): SpecNode {
    this.locals=new Map();const children:SpecNode[]=[paragraph('Tests '+this.type(suite.type)+'. Each case gets fresh setup and dependencies.')];
      for(const group of suite.groups) {
      this.locals=new Map();const groupChildren:SpecNode[]=[];
      if(group.setup.length)groupChildren.push(paragraph('Setup for each case:'),flow(group.setup.flatMap(entry=>
        entry.kind==='bind'||entry.kind==='include'?[step(this.providerLine(entry))]:this.statement(entry as Stmt))));
      const setupLocals=new Map(this.locals);
      for(const test of group.cases) {
        this.locals=new Map(setupLocals);const caseChildren:SpecNode[]=[];
        if(test.parameters)caseChildren.push(paragraph('Run once for each row of '+test.rows!.map(row=>this.expression(row)).join('; ')+'. Bind row positions to '+test.parameters.map(code).join(', ')+'.'));
        caseChildren.push(flow(this.statements(test.body)));
        groupChildren.push(section(code(test.name),4,caseChildren,undefined,this.source(test.span)));
      }
      children.push(section(code(group.name),3,groupChildren));
    }
    return this.heading(this.testTitle(suite),suite.span,2,children);
  }
  private testTitle(suite:TestDecl): string {
    return 'test '+suite.type.name+(suite.name===suite.type.name?'':' '+suite.name);
  }
  private dependencySurface(): SpecNode|undefined {
    if(!this.used.size)return;
    const entries=[...this.used.values()].sort((a,b)=>compare(relative(this.checked.project.root,this.docs.get(a.def.file)!)+':'+a.def.name,relative(this.checked.project.root,this.docs.get(b.def.file)!)+':'+b.def.name));
    const groups=new Map<string,string[]>();
    for(const entry of entries) {
      const def=entry.def, node=def.node;
      const imported=this.file.items.find(item=>item.kind==='import'&&(this.checked.project.imports.get(item)??[]).some(imported=>imported.id===def.id));
      const origin=imported?.kind==='import'?code(imported.from.join('.'))+(imported.everything?' through import everything':''):'';
      const names=[this.link(def)];
      const members=[...entry.operations].sort((a,b)=>compare(a.name,b.name)).map(method=>this.link(def,def.name+'.'+method.name,method.name));
      members.push(...[...entry.fields].sort(compare).map(name=>code(name)));
      if(members.length)names[0]+=' ('+coordinate(members)+')';
      const group=groups.get(origin)??[];group.push(...names);groups.set(origin,group);
    }
    return section('Dependencies',2,[...[...groups].map(([origin,names])=>paragraph(
      'It uses '+coordinate(names)+(origin?' from '+origin:'')+'.')),paragraph('These links explain the full dependency contracts.')]);
  }
  render(): string {
    const exports=this.file.items.filter(item=>item.kind==='export');
    const declarations=this.file.items.filter(item=>['class','interface','interceptor','function','composition'].includes(item.kind));
    const providers=this.file.items.filter(item=>item.kind==='bind'||item.kind==='include');
    const startup=this.file.items.filter(item=>item.kind!=='import'&&item.kind!=='export'&&item.kind!=='test'&&item.kind!=='bind'&&item.kind!=='include'&&!declarations.includes(item));
    const children:SpecNode[]=[];
    if(declarations.some(item=>item.kind==='function'&&item.endpoint))children.push(paragraph(
      'Plain handler results default to HTTP 200 unless another status is declared. HttpResponse values choose their own status. Unhandled request failures return HTTP 500 and cancel the request tasks.'));
    if(basename(this.file.path)==='main.aug') {
      const project=this.checked.project;
      if(project.files.get(this.file.path)?.items.some(item=>item.kind==='serve'))children.push(section('HTTP configuration',2,[paragraph(
        `Listen on ${code(project.config.web.host)}. Limit request bodies to ${project.config.web.body_limit} bytes and buffered responses to ${project.config.web.response_limit} bytes. `+
        (project.config.web.tls.certificate?'Use TLS. ':'')+
        (project.config.web.http3?'Enable HTTP/3. ':'')+
        (project.config.openapi.enabled?`Serve OpenAPI at ${code(project.config.openapi.path)} and API docs at ${code(project.config.openapi.docs)}. `:''))]));
    }
    // Build the checked explanation first; rendering decides all spacing.
    if(exports.length)children.push(section('Exports',2,exports.map(item=>paragraph(this.exportLine(item as Extract<TopLevel,{kind:'export'}>)))));
    if(providers.length)children.push(section('Providers',2,providers.map(item=>paragraph(this.providerLine(item as BindDecl|Extract<TopLevel,{kind:'include'}>)))));
    if(startup.length)children.push(section('Startup',2,[flow(startup.flatMap(item=>this.statement(item as Stmt)))]));
    children.push(...declarations.sort((a,b)=>Number('name' in a&&a.name.startsWith('_'))-Number('name' in b&&b.name.startsWith('_'))).map(item=>this.declaration(item)));
    children.push(...this.file.items.filter(item=>item.kind==='test').map(item=>this.declaration(item)));
    if(!children.length)children.push(paragraph('This file declares no operations.'));
    // Links may add inherited operation owners. Walk until the surface is closed.
    const surfaceSize=()=>[...this.used.values()].reduce((size,entry)=>size+1+entry.operations.size+entry.fields.size+Number(entry.constructed??false),0);
    let surface:SpecNode|undefined, size=-1;
    do {size=surfaceSize();surface=this.dependencySurface();} while(surfaceSize()!==size);
    if(surface)children.push(surface);
    const builtins=this.builtinSurface();if(builtins)children.push(builtins);
    return generated+'\n\n'+renderSpecTree(section(code(basename(this.file.path)),1,children));
  }
  private builtinSurface(): SpecNode|undefined {
    if(!this.builtins.size&&!this.properties.size)return;
    return paragraph('Built-in operations follow the [language reference](https://greenpandastudios.github.io/augscript/language-constructs).');
  }
}

/** Refresh pointers and artifacts atomically, or check drift without writing; protect handwritten documents. */
export function updateSpecs(checked:CheckedProject, check=false, options:SpecOptions={}): {files:number; stale:string[]} {
  const outputs=generateSpecs(checked,options), root=checked.project.root;
  const manifest=join(root,'.aug-spec','manifest.json');
  let previous:string[]=[];
  if(options.manifest!==false&&existsSync(manifest)) {
    const saved=JSON.parse(readFileSync(manifest,'utf8')) as {format:number;files:string[]};
    if(saved.format!==1||!Array.isArray(saved.files)||saved.files.some(path=>typeof path!=='string'||relative(root,resolve(root,path)).startsWith('..')||!path.endsWith('.aug')&&!path.endsWith('.aug.md')))
      throw new Error('Invalid generated specification manifest');
    previous=saved.files.map(path=>resolve(root,path));
  }
  const artifacts=outputs.filter(output=>output.kind!=='source-hint');
  const names=new Set(artifacts.map(output=>output.path));
  const removed=previous.filter(path=>!names.has(path)&&existsSync(path));
  const stale=outputs.filter(output=>!existsSync(output.path)||readFileSync(output.path,'utf8')!==output.text).map(output=>relative(root,output.path));
  stale.push(...removed.map(path=>relative(root,path)));
  const manifestText=JSON.stringify({format:1,files:artifacts.map(output=>relative(root,output.path).replaceAll('\\','/')),digest:hash(artifacts.map(output=>output.text).join('\0'))},null,2)+'\n';
  if(options.manifest!==false&&(!existsSync(manifest)||readFileSync(manifest,'utf8')!==manifestText))stale.push('.aug-spec/manifest.json');
  if(check)return {files:outputs.length,stale};
  if(options.manifest!==false&&(existsSync(dirname(manifest))&&lstatSync(dirname(manifest)).isSymbolicLink()||existsSync(manifest)&&lstatSync(manifest).isSymbolicLink()))
    throw new Error('Specification manifest must not be a symbolic link');
  for(const output of outputs) {
    let parent=dirname(output.path);
    // Trust the project root, including platform aliases such as macOS /var.
    while(parent!==root&&!relative(root,parent).startsWith('..')&&parent!==dirname(parent)) {
      if(existsSync(parent)&&lstatSync(parent).isSymbolicLink())throw new Error(`Specification output directory is a symbolic link: ${parent}`);
      parent=dirname(parent);
    }
    if(existsSync(output.path)) {
      if(lstatSync(output.path).isSymbolicLink())throw new Error(`Specification output is a symbolic link: ${output.path}`);
      const text=readFileSync(output.path,'utf8');
      if(output.kind==='source-hint') {
        if(text!==checked.project.files.get(output.source)?.source)throw new Error('Source changed during compilation; retry before generating specifications');
      }else if(!text.startsWith(generated)&&!text.startsWith(copied))throw new Error(`Refusing to overwrite handwritten file ${output.path}`);
    }
  }
  for(const output of outputs) {
    if(existsSync(output.path)&&readFileSync(output.path,'utf8')===output.text)continue;
    mkdirSync(dirname(output.path),{recursive:true});
    const temporary=output.path+'.aug-spec-tmp';
    let created=false;
    try {writeFileSync(temporary,output.text,{flag:'wx',mode:output.kind==='source-hint'?lstatSync(output.path).mode:undefined});created=true;renameSync(temporary,output.path);} finally {if(created&&existsSync(temporary))rmSync(temporary);}
  }
  for(const path of removed) {
    const text=readFileSync(path,'utf8');
    if(text.startsWith(generated)||text.startsWith(copied))rmSync(path);
  }
  if(options.manifest!==false) {
    mkdirSync(dirname(manifest),{recursive:true});
    if(!existsSync(manifest)||readFileSync(manifest,'utf8')!==manifestText) {
      const temporary=manifest+'.aug-spec-tmp';
      let created=false;
      try {writeFileSync(temporary,manifestText,{flag:'wx'});created=true;renameSync(temporary,manifest);} finally {if(created&&existsSync(temporary))rmSync(temporary);}
    }
  }
  return {files:outputs.length,stale:[]};
}
