import {dirname,join,relative} from 'node:path';
import {realpathSync} from 'node:fs';
import {expressionChildren,initializationOf,isStatement,type ClassDecl,type Expr,type MethodDecl,type SourceFile,type Span,type Stmt} from './ast.ts';
import type {CheckedProject} from './checker.ts';
import {callableErrors} from './contracts.ts';
import {semanticGraph,semanticSourcePath,type SemanticEdge,type SemanticSymbol} from './symbols.ts';

const compare=(a:string,b:string)=>a<b?-1:a>b?1:0;
const url=(path:string)=>path.replaceAll('\\','/').split('/').map(encodeURIComponent).join('/');
const markdown=(text:string)=>text.replace(/[\\\`*_[\]<>|]/g,char=>'\\'+char);
const label=(text:string)=>text.replace(/\s+/g,' ').replace(/^(.{117}).{4,}$/,'$1…').replace(/[&;"<>{}\[\]\`#\\]/g,char=>'#'+char.codePointAt(0)+';');
const sequenceAnchor=(name:string)=>'sequence-'+[...name].map(char=>/[A-Za-z0-9_.-]/.test(char)?char:'-'+char.codePointAt(0)!.toString(16)+'-').join('');
const generated='<!-- Generated by aug spec. Edit the August source, then regenerate. -->';
const limits={nodes:18,edges:30,participants:12,steps:24};
export interface DiagramOutput {path:string;text:string;source:string;kind:'diagram'}
interface DiagramLinks {root?:string;docs:ReadonlyMap<string,string>;sources:ReadonlyMap<string,string>;offsets:ReadonlyMap<string,number>}
interface GraphEdge {from:string;to:string;label:string}
interface GraphNode {id:string;label:string}
type SequenceToken={kind:'message'|'note';target?:string;text:string;async?:boolean}|{kind:'open';text:string}|{kind:'else';text:string}|{kind:'close'};
type FlowExit='return'|'throw'|'break'|'continue';
interface Flow {fallsThrough:boolean;exits:Set<FlowExit>}
const normalFlow=():Flow=>({fallsThrough:true,exits:new Set()});
const terminalFlow=(exit:FlowExit):Flow=>({fallsThrough:false,exits:new Set([exit])});
const mergeFlows=(flows:Flow[]):Flow=>({fallsThrough:flows.some(flow=>flow.fallsThrough),exits:new Set(flows.flatMap(flow=>[...flow.exits]))});
interface Sequence {name:string;span:Span;tokens:SequenceToken[];participants:Map<string,string>}

/** Deterministic checked relationships and source-order sequences; foreign/dynamic calls remain boundaries. */
export function generateDiagrams(checked:CheckedProject,files:SourceFile[],links:DiagramLinks):DiagramOutput[] {
  const project=checked.project,root=links.root??(project.library?realpathSync(project.root):project.root),index=join(root,'.aug-spec','diagrams','index.md');
  const graph=semanticGraph(checked,true),symbols=new Map(graph.symbols.map(symbol=>[symbol.id,symbol]));
  const sourceFiles=new Map([...project.files.values()].map(file=>[semanticSourcePath(checked,file.path),file]));
  const paths=new Map(files.map(file=>[file.path,links.docs.get(file.path)!.slice(0,-3)+'.diagrams.md']));
  const nodeIds=new WeakMap<object,string>();
  for(const def of project.definitions.values()){
    nodeIds.set(def.node,def.id);
    if('methods' in def.node)for(const method of def.node.methods)nodeIds.set(method,def.id+'/method/'+method.name);
  }
  const display=(symbol:SemanticSymbol)=>symbol.owner&&symbols.has(symbol.owner)?symbols.get(symbol.owner)!.name+'.'+symbol.name:symbol.name;
  const fileOf=(id:string)=>symbols.get(id)?.location.file??(id.startsWith('module:')?id.slice(7):undefined);
  const locationLink=(page:string,span:Span)=>{
    const source=links.sources.get(span.file);if(!source)return '';
    const offset=links.offsets.get(span.file)??(source===span.file?0:1);
    return url(relative(dirname(page),source))+'#L'+(span.line+offset);
  };
  const linkTo=(page:string,file:SourceFile,text=semanticSourcePath(checked,file.path),diagram=true)=>
    '['+markdown(text)+']('+url(relative(dirname(page),diagram?paths.get(file.path)!:links.docs.get(file.path)!))+')';
  const related=(edge:SemanticEdge)=>['call','callback-call','forward','injected','implements','inherits','interceptor'].includes(edge.kind);
  const actionSites=new Set([...checked.actions.keys()].map(expr=>semanticSourcePath(checked,expr.span.file)+':'+expr.span.start+':'+expr.span.end));
  const relationLabel=(edge:SemanticEdge)=>actionSites.has(edge.location.file+':'+edge.location.start+':'+edge.location.end)?'defers HTTP call to':({call:'calls','callback-call':'callback','forward':'forwards to',injected:'depends on',implements:'implements',inherits:'extends',interceptor:'intercepted by'}[edge.kind as 'call'])??edge.kind;
  const graphNodes=(ids:Set<string>):GraphNode[]=>[...ids].sort(compare).map(id=>{
    const symbol=symbols.get(id);
    return {id,label:symbol?display(symbol)+' · '+symbol.location.file:id.replace(/^module:/,'')};
  });
  const relationshipGraphs=(edges:GraphEdge[],nodes:GraphNode[])=>renderGraphs(nodes,edges);
  const own=files.filter(file=>links.sources.get(file.path)===file.path).sort((a,b)=>compare(semanticSourcePath(checked,a.path),semanticSourcePath(checked,b.path)));
  const ownPaths=new Set(own.map(file=>semanticSourcePath(checked,file.path)));
  const area=(path:string)=>path.startsWith('august/')?'August library':path.startsWith('package/')?path.split('/').slice(0,path.split('/')[1].startsWith('@')?3:2).join('/'):path.includes('/')?path.split('/')[0]:'Project root';
  const moduleEdges=new Map<string,GraphEdge>(),areaEdges=new Map<string,GraphEdge>(),areas=new Set<string>();
  for(const file of own)areas.add(area(semanticSourcePath(checked,file.path)));
  for(const edge of graph.relationships.filter(edge=>related(edge)||edge.kind==='import'||edge.kind==='export'||edge.kind==='internal')){
    const from=fileOf(edge.from),to=fileOf(edge.to);if(!from||!to||from===to||!ownPaths.has(from))continue;
    moduleEdges.set(from+'\0'+to,{from,to,label:'uses'});
    const a=area(from),b=area(to);areas.add(a);areas.add(b);if(a!==b)areaEdges.set(a+'\0'+b,{from:a,to:b,label:'uses'});
  }
  const outputs:DiagramOutput[]=[];
  const moduleIds=new Set([...own.map(file=>semanticSourcePath(checked,file.path)),...[...moduleEdges.values()].flatMap(edge=>[edge.from,edge.to])]);
  let overview=generated+'\n\n# Project diagrams\n\nRead the areas first, then open a module for its class interactions, API calls and sequences. Follow an operation to its specification and source.\n\n'+
    'These are checked static views. Arrows describe possible calls, not an execution trace. Interface implementations, callbacks and foreign internals are not guessed. Tests are described in the adjacent specifications.\n\n'+
    '## Areas\n\n'+relationshipGraphs([...areaEdges.values()],[...areas].sort(compare).map(id=>({id,label:id})))+
    '\n## Modules\n\n'+relationshipGraphs([...moduleEdges.values()],[...moduleIds].sort(compare).map(id=>({id,label:id})))+
    '\n## Open a module\n\n| Module | Diagrams | Specification |\n| --- | --- | --- |\n'+own.map(file=>'| '+markdown(semanticSourcePath(checked,file.path))+' | '+linkTo(index,file,'Interactions and sequences')+' | '+linkTo(index,file,'Explanation',false)+' |').join('\n')+'\n';
  const endpoints=own.flatMap(file=>file.items.filter((item):item is MethodDecl=>item.kind==='function'&&!!item.endpoint).map(node=>({file,node})));
  if(endpoints.length)overview+='\n## HTTP APIs\n\n| API | Operation |\n| --- | --- |\n'+endpoints.map(({file,node})=>'| '+markdown(node.endpoint!.method+' '+node.endpoint!.path)+' | '+linkTo(index,file,node.name).replace(/\)$/, '#'+sequenceAnchor(node.name)+')')+' |').join('\n')+'\n';
  outputs.push({path:index,text:overview,source:own[0]?.path??project.main?.path??root,kind:'diagram'});
  for(const file of files.sort((a,b)=>compare(semanticSourcePath(checked,a.path),semanticSourcePath(checked,b.path)))){
    const page=paths.get(file.path)!,identity=semanticSourcePath(checked,file.path);
    const relations=graph.relationships.filter(edge=>edge.location.file===identity&&related(edge)&&symbols.has(edge.to));
    const classes=new Set<string>(),classEdges:GraphEdge[]=[];
    const owner=(id:string)=>{const symbol=symbols.get(id);return symbol?.owner&&['class','interface','interceptor'].includes(symbols.get(symbol.owner)?.kind??'')?symbol.owner:id;};
    for(const def of project.definitions.values())if(def.file===file.path&&['class','interface','resource','interceptor'].includes(def.node.kind))classes.add(def.id);
    for(const edge of relations){
      const from=owner(edge.from),to=owner(edge.to);
      if(classes.has(from)||['class','interface','interceptor','resource'].includes(symbols.get(to)?.kind??'')){
        classes.add(from);classes.add(to);classEdges.push({from,to,label:relationLabel(edge)});
      }
    }
    // Constructor dependencies are fields, not standalone callable parameters.
    for(const def of project.definitions.values())if(def.file===file.path&&def.node.kind==='class')for(const field of def.node.fields){
      const target=checked.resolvedTypes.get(field.type)?.def;if(!target)continue;
      classes.add(target.id);classEdges.push({from:def.id,to:target.id,label:(field.injected?'depends on ':'holds ')+field.name});
    }
    const apiEdges=relations.filter(edge=>['call','callback-call','forward','interceptor'].includes(edge.kind)).map(edge=>({from:edge.from,to:edge.to,label:relationLabel(edge)}));
    const apiIds=new Set(apiEdges.flatMap(edge=>[edge.from,edge.to]));
    for(const def of project.definitions.values())if(def.file===file.path){
      if(def.node.kind==='function')apiIds.add(def.id);
      if('methods' in def.node)for(const method of def.node.methods)apiIds.add(nodeIds.get(method)!);
    }
    let text=generated+'\n\n# '+markdown(identity)+' diagrams\n\n[Project overview]('+url(relative(dirname(page),index))+') · '+linkTo(page,file,'Compiled explanation',false)+'\n\n'+
      '## Class interactions\n\n'+relationshipGraphs(classEdges,graphNodes(classes))+
      '\n## API calls\n\n'+relationshipGraphs(apiEdges,graphNodes(apiIds))+
      '\n## Sequences\n\nCall arrows identify checked targets; loop and branch frames determine when they run. Open that target’s module to follow its implementation. Branches describe alternatives; loops describe repeated work. Native calls and interface dispatch stop at their declared contracts. Exit notes end that path; enclosing recovery and cleanup remain visible.\n\n';
    const sequences:Sequence[]=[];
    const build=(name:string,span:Span,body:Stmt[],method?:MethodDecl,constructor?:ClassDecl)=>{
      const writer=new SequenceWriter(checked,file,nodeIds,symbols,!!constructor);
      if(constructor?.fields.length)writer.note('Receive fields: '+constructor.fields.map(field=>(field.injected?'injected ':'')+field.name).join(', '));
      const layers=constructor&&checked.interceptorPlans.get(constructor);
      if(layers?.length)writer.note('Constructor layers: '+layers.map(layer=>layer.definition.name).join(', ')+'; may stop or change delegation; see specification');
      if(method?.endpoint)writer.note(method.endpoint.method+' '+method.endpoint.path+(method.endpoint.streams?' · streaming':''));
      if(method&&(checked.interceptorPlans.get(method)?.length||checked.httpPolicies.get(method)?.length))
        writer.note('Applied layers: '+[...(checked.httpPolicies.get(method)??[]).map(layer=>layer.name),...(checked.interceptorPlans.get(method)??[]).map(layer=>layer.definition.name)].join(', ')+'; may stop or change delegation; see specification');
      if(method?.forward){
        const target=method.forward.targetId&&symbols.get(method.forward.targetId);
        if(target)writer.message(target.id,display(target),'forward '+method.forward.target);
      }else writer.statements(body);
      if(method){
        const errors=callableErrors(checked,method);if(errors.length)writer.note('May leave with checked errors: '+errors.join(', '));
        if(method.endpoint)writer.note('HTTP result follows declared response and error mapping; unhandled request failure returns 500');
        if(!method.body&&!method.forward)writer.note(method.externC?'Native implementation; only the declared contract is known':'Interface contract; implementation selected at runtime');
      }
      if(!writer.tokens.length)writer.note('No calls in this operation; see the source and specification');
      sequences.push({name,span,tokens:writer.tokens,participants:writer.participants});
    };
    const startup=file.items.filter(isStatement);if(startup.length)build('Startup',startup[0].span,startup);
    for(const item of file.items){
      if(item.kind==='function')build(item.name,item.span,item.body??[],item);
      if(item.kind==='class'){
        build(item.name+' constructor',item.span,initializationOf(item),undefined,item);
        for(const method of item.methods)build(item.name+'.'+method.name,method.span,method.body??[],method);
      }else if(item.kind==='interface'||item.kind==='interceptor')for(const method of item.methods)build(item.name+'.'+method.name,method.span,method.body??[],method);
    }
    if(!sequences.length)text+='This module declares no executable operations.\n';
    for(const sequence of sequences){
      text+='<a id="'+sequenceAnchor(sequence.name)+'"></a>\n\n### '+markdown(sequence.name)+'\n\n[Source]('+locationLink(page,sequence.span)+')\n\n'+renderSequence(sequence);
    }
    const references=[...new Set(relations.map(edge=>edge.to))].sort(compare);
    if(references.length)text+='## Called contracts\n\n'+references.map(id=>{
      const symbol=symbols.get(id)!,target=sourceFiles.get(symbol.location.file);if(!target)return '';
      const local=paths.has(target.path),def=project.definitions.get(symbol.owner??id);
      const hasSequence=symbol.kind==='function'||symbol.kind==='method'&&['class','interface','interceptor'].includes(def?.node.kind??'')||symbol.kind==='class';
      const fragment=local&&hasSequence?'#'+sequenceAnchor(symbol.kind==='class'?symbol.name+' constructor':display(symbol)):'';
      return '- ['+markdown(display(symbol))+']('+url(relative(dirname(page),local?paths.get(target.path)!:links.docs.get(target.path)!))+fragment+') — '+markdown(symbol.location.file);
    }).filter(Boolean).join('\n')+'\n';
    outputs.push({path:page,text,source:file.path,kind:'diagram'});
  }
  return outputs;
}

function renderGraphs(nodes:GraphNode[],edges:GraphEdge[]):string{
  const distinct=[...new Map(edges.map(edge=>[edge.from+'\0'+edge.to+'\0'+edge.label,edge])).values()].sort((a,b)=>compare(a.from,b.from)||compare(a.to,b.to)||compare(a.label,b.label));
  const labels=new Map(nodes.map(node=>[node.id,node.label])),all=[...labels.keys()].sort(compare);
  if(!all.length)return 'No relationships at this level.\n';
  const chunks:{nodes:Set<string>;edges:GraphEdge[]}[]=[];let current={nodes:new Set<string>(),edges:[] as GraphEdge[]};
  const flush=()=>{if(current.nodes.size)chunks.push(current);current={nodes:new Set<string>(),edges:[]};};
  for(const edge of distinct){
    const size=new Set([...current.nodes,edge.from,edge.to]).size;
    if(size>limits.nodes||current.edges.length>=limits.edges)flush();
    current.nodes.add(edge.from);current.nodes.add(edge.to);current.edges.push(edge);
  }
  const covered=new Set(chunks.flatMap(chunk=>[...chunk.nodes]).concat([...current.nodes]));
  for(const id of all)if(!covered.has(id)){if(current.nodes.size>=limits.nodes)flush();current.nodes.add(id);}
  flush();
  return chunks.map((chunk,index)=>{
    const ids=new Map([...chunk.nodes].sort(compare).map((id,index)=>[id,'n'+index]));
    return (chunks.length>1?'#### View '+(index+1)+' of '+chunks.length+'\n\n':'')+
      '```mermaid\nflowchart TD\n'+[...ids].map(([id,key])=>'    '+key+'["'+label(labels.get(id)??id)+'"]').join('\n')+'\n'+
      chunk.edges.map(edge=>'    '+ids.get(edge.from)+' -->|"'+label(edge.label)+'"| '+ids.get(edge.to)).join('\n')+'\n```\n';
  }).join('\n');
}

/** Ordered body traversal deliberately does not inline callees or claim callback execution. */
class SequenceWriter {
  readonly tokens:SequenceToken[]=[];
  readonly participants=new Map<string,string>();
  private constructorState:boolean;
  private checked:CheckedProject; private file:SourceFile; private ids:WeakMap<object,string>; private symbols:Map<string,SemanticSymbol>;
  constructor(checked:CheckedProject,file:SourceFile,ids:WeakMap<object,string>,symbols:Map<string,SemanticSymbol>,constructorState=false){this.constructorState=constructorState;this.checked=checked;this.file=file;this.ids=ids;this.symbols=symbols;}
  note(text:string){this.tokens.push({kind:'note',text});}
  message(id:string,name:string,text:string,async=false){this.participants.set(id,name);this.tokens.push({kind:'message',target:id,text,async});}
  private text(expr:Expr){return this.file.source.slice(expr.span.start,expr.span.end).replace(/\s+/g,' ');}
  private block(text:string,body:()=>void){this.tokens.push({kind:'open',text});body();this.tokens.push({kind:'close'});}
  expression(expr:Expr,async=false):void{
    const mapping=this.checked.workerMaps.get(expr);
    if(mapping){
      expressionChildren(expr).forEach(child=>this.expression(child));
      this.note('Validate mapping bounds before scheduling; copy contiguous chunks to isolated heaps');
      this.block('loop Bounded chunk wave',()=>{this.message(mapping.transformation.id,mapping.transformation.name,'Transform each copied value once',true);this.note('Wait in input order; join this wave before starting the next; failure cancels and joins admitted jobs');});return;
    }
    if(expr.kind==='lambda'){this.note('Create callback; its body runs when invoked: '+this.text(expr));return;}
    if(expr.kind==='start'){this.expression(expr.call,true);this.note(expr.worker?'Worker starts with an isolated heap and copied data':'Task starts in the current scope');return;}
    if(expr.kind==='wait'){expr.tasks.forEach(task=>this.expression(task));this.note('Wait for '+expr.tasks.map(task=>this.text(task)).join(' and ')+'; failure cancels siblings and cleanup joins');return;}
    if(expr.kind==='binary'&&(expr.op==='&&'||expr.op==='||'||expr.op==='otherwise')){
      this.expression(expr.left);this.block('opt '+(expr.op==='&&'?'Left is true':expr.op==='||'?'Left is false':'Left is null'),()=>this.expression(expr.right));return;
    }
    if(expr.kind==='matchValue'){
      this.expression(expr.value);
      expr.cases.forEach((clause,index)=>{this.tokens.push({kind:index?'else':'open',text:(index?'':'alt ')+this.file.source.slice(clause.span.start,clause.result.span.start).trim()});this.expression(clause.result);});
      this.tokens.push({kind:'close'});return;
    }
    if(expr.kind==='comprehension'){this.expression(expr.iterable);this.block('loop Each selected item',()=>{if(expr.condition){this.expression(expr.condition);this.block('opt Filter matches '+this.text(expr.condition!),()=>this.expression(expr.projection));}else this.expression(expr.projection);});return;}
    if(expr.kind==='handle'){if(expr.call.kind==='call')for(const input of expr.call.args)if(input.kind!=='formInput')this.expression(input);const action=this.checked.actions.get(expr);this.note('Create browser action for '+(action?.endpoint.node.kind==='function'?action.endpoint.node.endpoint?.method+' '+action.endpoint.node.endpoint?.path:this.text(expr.call))+'; called on submission');return;}
    if(expr.kind==='markup'){const call=this.checked.markupCalls.get(expr);if(call){this.expression(call);return;}}
    expressionChildren(expr).forEach(child=>this.expression(child));
    if(expr.kind==='recordCopy'){
      const target=this.checked.expressionTypes.get(expr.base)?.def;
      if(target)this.message(target.id,target.name+' constructor','Construct '+target.name+' from copied fields with '+expr.fields.map(field=>field.name).join(', ')+'; run constructor validation');
      return;
    }
    if(expr.kind==='resolve'){this.note('Resolve '+expr.name+' from the declared composition');return;}
    if(expr.kind!=='call')return;
    const resolved=this.checked.resolvedCalls.get(expr),id=resolved&&this.ids.get(resolved.node);
    const plan=this.checked.callPlans.get(expr);
    const inputs=expr.args.map((_,index)=>{const param=resolved?.params.find((_,parameter)=>plan?.sourceIndices[parameter]===index);return expr.argLabels[index]??(param?.label??param?.name)??'input '+(index+1);}).join(', ');
    const symbol=id?this.symbols.get(id):undefined;
    if(resolved&&id){
      const name=symbol?.owner&&this.symbols.has(symbol.owner)?this.symbols.get(symbol.owner)!.name+'.'+symbol.name:resolved.node.name;
      this.message(id,name,resolved.node.name+'('+inputs+')'+(resolved.dispatch==='interface'?' · interface dispatch':'')+(resolved.node.kind==='function'&&resolved.node.externC?' · native boundary':''),async);
    }else this.message('operation:'+this.text(expr.callee),this.text(expr.callee),this.text(expr.callee)+'('+inputs+')'+(expr.callee.kind==='name'&&expr.callee.name==='next'?' · conditional interceptor delegation':''),async);
  }
  statements(body:Stmt[]):Flow {
    const exits=new Set<FlowExit>();
    for(const stmt of body){
      let flow=normalFlow();
      switch(stmt.kind){
        case 'if': {
          this.expression(stmt.test);this.tokens.push({kind:'open',text:'alt '+this.text(stmt.test)});
          const then=this.statements(stmt.then);let otherwise=normalFlow();
          if(stmt.otherwise.length){this.tokens.push({kind:'else',text:'otherwise'});otherwise=this.statements(stmt.otherwise);}
          this.tokens.push({kind:'close'});
          flow=stmt.test.kind==='literal'&&typeof stmt.test.value==='boolean'?(stmt.test.value?then:otherwise):mergeFlows([then,otherwise]);break;
        }
        case 'while': {
          let bodyFlow=normalFlow();
          this.block('loop While '+this.text(stmt.test),()=>{this.expression(stmt.test);bodyFlow=this.statements(stmt.body);});
          if(!(stmt.test.kind==='literal'&&stmt.test.value===false))flow={
            fallsThrough:stmt.test.kind==='literal'&&stmt.test.value===true?bodyFlow.exits.has('break'):true,
            exits:new Set([...bodyFlow.exits].filter(exit=>exit==='return'||exit==='throw')),
          };
          break;
        }
        case 'for': {
          this.expression(stmt.iterable);let bodyFlow=normalFlow();
          this.block('loop For each item in '+this.text(stmt.iterable),()=>{bodyFlow=this.statements(stmt.body);});
          flow={fallsThrough:true,exits:new Set([...bodyFlow.exits].filter(exit=>exit==='return'||exit==='throw'))};break;
        }
        case 'match': {
          this.expression(stmt.value);
          const branches=stmt.cases.map((clause,index)=>{
            this.tokens.push({kind:index?'else':'open',text:(index?'':'alt ')+'Match '+this.file.source.slice(clause.span.start,clause.body[0]?.span.start??clause.span.end).trim()});
            return this.statements(clause.body);
          });
          this.tokens.push({kind:'close'});flow=mergeFlows(branches);break;
        }
        case 'try': {
          let bodyFlow=normalFlow(),alwaysFlow=normalFlow();
          this.block('opt Try body; stops on a checked failure',()=>{bodyFlow=this.statements(stmt.body);});
          const handlers=stmt.catches.map(handler=>{let caught=normalFlow();this.block('opt Catch '+handler.type.name,()=>{caught=this.statements(handler.body);});return caught;});
          if(stmt.always)this.block('rect rgb(245, 240, 241)',()=>{this.note('Always: cleanup runs on success, failure, return or cancellation');alwaysFlow=this.statements(stmt.always!);});
          const pending=mergeFlows([bodyFlow,...handlers]);
          flow=alwaysFlow.fallsThrough?{fallsThrough:pending.fallsThrough,exits:new Set([...pending.exits,...alwaysFlow.exits])}:alwaysFlow;break;
        }
        case 'scope':
          this.block('rect rgb(245, 240, 241)',()=>{this.note('Enter task scope');flow=this.statements(stmt.body);this.note('Join tasks and release scoped resources');});break;
        case 'borrow':case 'unsafe':case 'lock':
          this.block('rect rgb(245, 240, 241)',()=>{if(stmt.kind==='lock')this.expression(stmt.value);this.note('Enter '+stmt.kind+' scope');flow=this.statements(stmt.body);this.note('Leave '+stmt.kind+' scope');});break;
        case 'assign':
          if(stmt.target.kind==='member')this.expression(stmt.target.object);
          this.expression(stmt.value);
          if(this.constructorState)this.note('Set '+(stmt.target.kind==='name'?stmt.target.name:this.text(stmt.target))+' to '+this.text(stmt.value));
          if(stmt.ownership==='own'||this.checked.inferredOwned.has(stmt))this.note('Own '+this.text(stmt.target)+'; release on scope exits');break;
        case 'expr':this.expression(stmt.expr);break;
        case 'return':case 'throw':
          if(stmt.value)this.expression(stmt.value);
          this.note((stmt.kind==='return'?'Return'+(stmt.value?' '+this.text(stmt.value):''):'Raise checked failure '+this.text(stmt.value))+'; required cleanup runs before exit');flow=terminalFlow(stmt.kind);break;
        case 'yield':this.expression(stmt.value);this.note('Send one stream item');break;
        case 'destructure':case 'freeze':this.expression(stmt.value);break;
        case 'serve':this.expression(stmt.port);this.note('Serve endpoints: '+stmt.names.join(', '));break;
        case 'break':case 'continue':this.note(stmt.kind==='break'?'Leave this loop':'Continue with the next iteration');flow=terminalFlow(stmt.kind);break;
      }
      for(const exit of flow.exits)exits.add(exit);
      if(!flow.fallsThrough)return {fallsThrough:false,exits};
    }
    return {fallsThrough:true,exits};
  }

}

function renderSequence(sequence:Sequence):string{
  const chunks:SequenceToken[][]=[];let current:SequenceToken[]=[],targets=new Set<string>(),steps=0;
  const stack:{text:string;otherwise?:string}[]=[];
  const flush=()=>{
    if(!current.length)return;
    chunks.push([...current,...stack.map(()=>({kind:'close' as const}))]);
    current=stack.flatMap(frame=>[{kind:'open' as const,text:frame.text},...(frame.otherwise?[{kind:'else' as const,text:frame.otherwise}]:[])]);
    current.push({kind:'note',text:'Sequence continued from the previous view'});
    targets=new Set();steps=1;
  };
  for(const token of sequence.tokens){
    if(token.kind==='message'||token.kind==='note'){
      const next=new Set([...targets,...(token.target?[token.target]:[])]);
      if(steps>=limits.steps||next.size>limits.participants-1)flush();
      if(token.target)targets.add(token.target);steps++;
    }
    current.push(token);
    if(token.kind==='open')stack.push({text:token.text});
    else if(token.kind==='else'){if(stack.length)stack[stack.length-1].otherwise=token.text;}
    else if(token.kind==='close')stack.pop();
  }
  if(current.length)chunks.push(current);
  return chunks.map((chunk,index)=>{
    const targets=[...new Set(chunk.flatMap(token=>token.kind==='message'&&token.target?[token.target]:[]))];
    const ids=new Map(targets.map((target,index)=>[target,'p'+(index+1)]));
    const lines=chunk.map(token=>{
      if(token.kind==='message')return 'p0'+(token.async?'-)': '->>')+ids.get(token.target!)+': '+label(token.text)+(token.async?' · start asynchronously':'');
      if(token.kind==='note')return 'Note over p0: '+label(token.text);
      if(token.kind==='open')return token.text.split(' ')[0]+' '+label(token.text.slice(token.text.indexOf(' ')+1));
      return token.kind==='else'?'else '+label(token.text):'end';
    });
    return (chunks.length>1?'#### Sequence '+(index+1)+' of '+chunks.length+' (continued)\n\n':'')+
      '```mermaid\nsequenceDiagram\n    participant p0 as '+label(sequence.name)+'\n'+
      targets.map(target=>'    participant '+ids.get(target)+' as '+label(sequence.participants.get(target)??target)).join('\n')+'\n'+
      lines.map(line=>'    '+line).join('\n')+'\n```\n\n';
  }).join('');
}
